// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file underlay_message.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_UNDERLAY_MESSAGE_H_
#define _FAST_DDS_GENERATED_UNDERLAY_MESSAGE_H_

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec(dllexport)
#else
#define eProsima_user_DllExport
#endif // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(underlay_message_SOURCE)
#define underlay_message_DllAPI __declspec(dllexport)
#else
#define underlay_message_DllAPI __declspec(dllimport)
#endif // underlay_message_SOURCE
#else
#define underlay_message_DllAPI
#endif // EPROSIMA_USER_DLL_EXPORT
#else
#define underlay_message_DllAPI
#endif // _WIN32

namespace eprosima
{
namespace fastcdr
{
class Cdr;
} // namespace fastcdr
} // namespace eprosima

/*!
 * @brief This class represents the structure UnderlayMessage defined by the user in the
 * IDL file.
 * @ingroup UNDERLAY_MESSAGE
 */
class UnderlayMessage
{
  public:
    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport UnderlayMessage();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~UnderlayMessage();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object UnderlayMessage that will be copied.
     */
    eProsima_user_DllExport UnderlayMessage(const UnderlayMessage &x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object UnderlayMessage that will be copied.
     */
    eProsima_user_DllExport UnderlayMessage(UnderlayMessage &&x);

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object UnderlayMessage that will be copied.
     */
    eProsima_user_DllExport UnderlayMessage &operator=(const UnderlayMessage &x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object UnderlayMessage that will be copied.
     */
    eProsima_user_DllExport UnderlayMessage &operator=(UnderlayMessage &&x);

    /*!
     * @brief Comparison operator.
     * @param x UnderlayMessage object to compare.
     */
    eProsima_user_DllExport bool operator==(const UnderlayMessage &x) const;

    /*!
     * @brief Comparison operator.
     * @param x UnderlayMessage object to compare.
     */
    eProsima_user_DllExport bool operator!=(const UnderlayMessage &x) const;

    /*!
     * @brief This function copies the value in member bytes
     * @param _bytes New value to be copied in member bytes
     */
    eProsima_user_DllExport void bytes(const std::vector<uint8_t> &_bytes);

    /*!
     * @brief This function moves the value in member bytes
     * @param _bytes New value to be moved in member bytes
     */
    eProsima_user_DllExport void bytes(std::vector<uint8_t> &&_bytes);

    /*!
     * @brief This function returns a constant reference to member bytes
     * @return Constant reference to member bytes
     */
    eProsima_user_DllExport const std::vector<uint8_t> &bytes() const;

    /*!
     * @brief This function returns a reference to member bytes
     * @return Reference to member bytes
     */
    eProsima_user_DllExport std::vector<uint8_t> &bytes();
    /*!
     * @brief This function copies the value in member type_name
     * @param _type_name New value to be copied in member type_name
     */
    eProsima_user_DllExport void type_name(const std::string &_type_name);

    /*!
     * @brief This function moves the value in member type_name
     * @param _type_name New value to be moved in member type_name
     */
    eProsima_user_DllExport void type_name(std::string &&_type_name);

    /*!
     * @brief This function returns a constant reference to member type_name
     * @return Constant reference to member type_name
     */
    eProsima_user_DllExport const std::string &type_name() const;

    /*!
     * @brief This function returns a reference to member type_name
     * @return Reference to member type_name
     */
    eProsima_user_DllExport std::string &type_name();
    /*!
     * @brief This function copies the value in member type_id
     * @param _type_id New value to be copied in member type_id
     */
    eProsima_user_DllExport void type_id(const std::string &_type_id);

    /*!
     * @brief This function moves the value in member type_id
     * @param _type_id New value to be moved in member type_id
     */
    eProsima_user_DllExport void type_id(std::string &&_type_id);

    /*!
     * @brief This function returns a constant reference to member type_id
     * @return Constant reference to member type_id
     */
    eProsima_user_DllExport const std::string &type_id() const;

    /*!
     * @brief This function returns a reference to member type_id
     * @return Reference to member type_id
     */
    eProsima_user_DllExport std::string &type_id();
    /*!
     * @brief This function sets a value in member stamp
     * @param _stamp New value for member stamp
     */
    eProsima_user_DllExport void stamp(double _stamp);

    /*!
     * @brief This function returns the value of member stamp
     * @return Value of member stamp
     */
    eProsima_user_DllExport double stamp() const;

    /*!
     * @brief This function returns a reference to member stamp
     * @return Reference to member stamp
     */
    eProsima_user_DllExport double &stamp();

    /*!
     * @brief This function sets a value in member seq
     * @param _seq New value for member seq
     */
    eProsima_user_DllExport void seq(int32_t _seq);

    /*!
     * @brief This function returns the value of member seq
     * @return Value of member seq
     */
    eProsima_user_DllExport int32_t seq() const;

    /*!
     * @brief This function returns a reference to member seq
     * @return Reference to member seq
     */
    eProsima_user_DllExport int32_t &seq();

    /*!
     * @brief This function returns the maximum serialized size of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
        size_t current_alignment = 0);

    /*!
     * @brief This function returns the serialized size of a data depending on the buffer
     * alignment.
     * @param data Data which is calculated its serialized size.
     * @param current_alignment Buffer alignment.
     * @return Serialized size.
     */
    eProsima_user_DllExport static size_t getCdrSerializedSize(
        const UnderlayMessage &data, size_t current_alignment = 0);

    /*!
     * @brief This function serializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serialize(eprosima::fastcdr::Cdr &cdr) const;

    /*!
     * @brief This function deserializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void deserialize(eprosima::fastcdr::Cdr &cdr);

    /*!
     * @brief This function returns the maximum serialized size of the Key of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
        size_t current_alignment = 0);

    /*!
     * @brief This function tells you if the Key has been defined for this type
     */
    eProsima_user_DllExport static bool isKeyDefined();

    /*!
     * @brief This function serializes the key members of an object using CDR
     * serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serializeKey(eprosima::fastcdr::Cdr &cdr) const;

  private:
    std::vector<uint8_t> m_bytes;
    std::string m_type_name;
    std::string m_type_id;
    double m_stamp;
    int32_t m_seq;
};

#endif // _FAST_DDS_GENERATED_UNDERLAY_MESSAGE_H_