// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apa_msgs/objects.proto

#ifndef PROTOBUF_INCLUDED_apa_5fmsgs_2fobjects_2eproto
#define PROTOBUF_INCLUDED_apa_5fmsgs_2fobjects_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h> // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "apa_msgs/common.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_apa_5fmsgs_2fobjects_2eproto

namespace protobuf_apa_5fmsgs_2fobjects_2eproto
{
// Internal implementation detail -- do not use these members.
struct TableStruct
{
    static const ::google::protobuf::internal::ParseTableField entries[];
    static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
    static const ::google::protobuf::internal::ParseTable schema[2];
    static const ::google::protobuf::internal::FieldMetadata field_metadata[];
    static const ::google::protobuf::internal::SerializationTable serialization_table[];
    static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
} // namespace protobuf_apa_5fmsgs_2fobjects_2eproto
namespace raincom
{
namespace apa
{
namespace msgs
{
class Object;
class ObjectDefaultTypeInternal;
extern ObjectDefaultTypeInternal _Object_default_instance_;
class Objects;
class ObjectsDefaultTypeInternal;
extern ObjectsDefaultTypeInternal _Objects_default_instance_;
} // namespace msgs
} // namespace apa
} // namespace raincom
namespace google
{
namespace protobuf
{
template <>
::raincom::apa::msgs::Object *Arena::CreateMaybeMessage<::raincom::apa::msgs::Object>(
    Arena *);
template <>
::raincom::apa::msgs::Objects *Arena::CreateMaybeMessage<::raincom::apa::msgs::Objects>(
    Arena *);
} // namespace protobuf
} // namespace google
namespace raincom
{
namespace apa
{
namespace msgs
{

enum Object_Clf
{
    Object_Clf_UNKNOWN_CLF                             = 0,
    Object_Clf_LEFT_VER_SLOT                           = 1,
    Object_Clf_RIGHT_VER_SLOT                          = 2,
    Object_Clf_LEFT_PAR_SLOT                           = 3,
    Object_Clf_RIGHT_PAR_SLOT                          = 4,
    Object_Clf_SLB                                     = 5,
    Object_Clf_CONE                                    = 6,
    Object_Clf_PL_CLOSED                               = 7,
    Object_Clf_PL_OPENED                               = 8,
    Object_Clf_OPLB_R                                  = 9,
    Object_Clf_OPLB_I                                  = 10,
    Object_Clf_HANDICAP                                = 11,
    Object_Clf_PVC                                     = 12,
    Object_Clf_CARTON                                  = 13,
    Object_Clf_CHAIR                                   = 14,
    Object_Clf_PEDSTRAIN                               = 15,
    Object_Clf_BUCKET                                  = 16,
    Object_Clf_E_BIKE                                  = 17,
    Object_Clf_STOP_SIGN                               = 18,
    Object_Clf_CHARGING_STOP                           = 19,
    Object_Clf_DECEL_STRIP                             = 20,
    Object_Clf_BUMPER                                  = 21,
    Object_Clf_FENCE                                   = 22,
    Object_Clf_WHEEL_CHAIR                             = 23,
    Object_Clf_FIRE_KIT                                = 24,
    Object_Clf_BIKE                                    = 25,
    Object_Clf_SHOPPING_CART                           = 26,
    Object_Clf_WARNING_POST                            = 27,
    Object_Clf_BOLLARDS                                = 28,
    Object_Clf_Object_Clf_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
    Object_Clf_Object_Clf_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Object_Clf_IsValid(int value);
const Object_Clf Object_Clf_Clf_MIN = Object_Clf_UNKNOWN_CLF;
const Object_Clf Object_Clf_Clf_MAX = Object_Clf_BOLLARDS;
const int Object_Clf_Clf_ARRAYSIZE  = Object_Clf_Clf_MAX + 1;

const ::google::protobuf::EnumDescriptor *Object_Clf_descriptor();
inline const ::std::string &Object_Clf_Name(Object_Clf value)
{
    return ::google::protobuf::internal::NameOfEnum(Object_Clf_descriptor(), value);
}
inline bool Object_Clf_Parse(const ::std::string &name, Object_Clf *value)
{
    return ::google::protobuf::internal::ParseNamedEnum<Object_Clf>(
        Object_Clf_descriptor(), name, value);
}
// ===================================================================

class Object : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:raincom.apa.msgs.Object)
                                                   */
{
  public:
    Object();
    virtual ~Object();

    Object(const Object &from);

    inline Object &operator=(const Object &from)
    {
        CopyFrom(from);
        return *this;
    }
#if LANG_CXX11
    Object(Object &&from) noexcept : Object() { *this = ::std::move(from); }

    inline Object &operator=(Object &&from) noexcept
    {
        if (GetArenaNoVirtual() == from.GetArenaNoVirtual())
        {
            if (this != &from)
                InternalSwap(&from);
        }
        else
        {
            CopyFrom(from);
        }
        return *this;
    }
#endif
    static const ::google::protobuf::Descriptor *descriptor();
    static const Object &default_instance();

    static void InitAsDefaultInstance(); // FOR INTERNAL USE ONLY
    static inline const Object *internal_default_instance()
    {
        return reinterpret_cast<const Object *>(&_Object_default_instance_);
    }
    static constexpr int kIndexInFileMessages = 0;

    void Swap(Object *other);
    friend void swap(Object &a, Object &b) { a.Swap(&b); }

    // implements Message ----------------------------------------------

    inline Object *New() const final { return CreateMaybeMessage<Object>(NULL); }

    Object *New(::google::protobuf::Arena *arena) const final
    {
        return CreateMaybeMessage<Object>(arena);
    }
    void CopyFrom(const ::google::protobuf::Message &from) final;
    void MergeFrom(const ::google::protobuf::Message &from) final;
    void CopyFrom(const Object &from);
    void MergeFrom(const Object &from);
    void Clear() final;
    bool IsInitialized() const final;

    size_t ByteSizeLong() const final;
    bool MergePartialFromCodedStream(
        ::google::protobuf::io::CodedInputStream *input) final;
    void SerializeWithCachedSizes(
        ::google::protobuf::io::CodedOutputStream *output) const final;
    ::google::protobuf::uint8 *InternalSerializeWithCachedSizesToArray(
        bool deterministic, ::google::protobuf::uint8 *target) const final;
    int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
    void SharedCtor();
    void SharedDtor();
    void SetCachedSize(int size) const final;
    void InternalSwap(Object *other);

  private:
    inline ::google::protobuf::Arena *GetArenaNoVirtual() const { return NULL; }
    inline void *MaybeArenaPtr() const { return NULL; }

  public:
    ::google::protobuf::Metadata GetMetadata() const final;

    // nested types ----------------------------------------------------

    typedef Object_Clf Clf;
    static const Clf UNKNOWN_CLF    = Object_Clf_UNKNOWN_CLF;
    static const Clf LEFT_VER_SLOT  = Object_Clf_LEFT_VER_SLOT;
    static const Clf RIGHT_VER_SLOT = Object_Clf_RIGHT_VER_SLOT;
    static const Clf LEFT_PAR_SLOT  = Object_Clf_LEFT_PAR_SLOT;
    static const Clf RIGHT_PAR_SLOT = Object_Clf_RIGHT_PAR_SLOT;
    static const Clf SLB            = Object_Clf_SLB;
    static const Clf CONE           = Object_Clf_CONE;
    static const Clf PL_CLOSED      = Object_Clf_PL_CLOSED;
    static const Clf PL_OPENED      = Object_Clf_PL_OPENED;
    static const Clf OPLB_R         = Object_Clf_OPLB_R;
    static const Clf OPLB_I         = Object_Clf_OPLB_I;
    static const Clf HANDICAP       = Object_Clf_HANDICAP;
    static const Clf PVC            = Object_Clf_PVC;
    static const Clf CARTON         = Object_Clf_CARTON;
    static const Clf CHAIR          = Object_Clf_CHAIR;
    static const Clf PEDSTRAIN      = Object_Clf_PEDSTRAIN;
    static const Clf BUCKET         = Object_Clf_BUCKET;
    static const Clf E_BIKE         = Object_Clf_E_BIKE;
    static const Clf STOP_SIGN      = Object_Clf_STOP_SIGN;
    static const Clf CHARGING_STOP  = Object_Clf_CHARGING_STOP;
    static const Clf DECEL_STRIP    = Object_Clf_DECEL_STRIP;
    static const Clf BUMPER         = Object_Clf_BUMPER;
    static const Clf FENCE          = Object_Clf_FENCE;
    static const Clf WHEEL_CHAIR    = Object_Clf_WHEEL_CHAIR;
    static const Clf FIRE_KIT       = Object_Clf_FIRE_KIT;
    static const Clf BIKE           = Object_Clf_BIKE;
    static const Clf SHOPPING_CART  = Object_Clf_SHOPPING_CART;
    static const Clf WARNING_POST   = Object_Clf_WARNING_POST;
    static const Clf BOLLARDS       = Object_Clf_BOLLARDS;
    static inline bool Clf_IsValid(int value) { return Object_Clf_IsValid(value); }
    static const Clf Clf_MIN       = Object_Clf_Clf_MIN;
    static const Clf Clf_MAX       = Object_Clf_Clf_MAX;
    static const int Clf_ARRAYSIZE = Object_Clf_Clf_ARRAYSIZE;
    static inline const ::google::protobuf::EnumDescriptor *Clf_descriptor()
    {
        return Object_Clf_descriptor();
    }
    static inline const ::std::string &Clf_Name(Clf value)
    {
        return Object_Clf_Name(value);
    }
    static inline bool Clf_Parse(const ::std::string &name, Clf *value)
    {
        return Object_Clf_Parse(name, value);
    }

    // accessors -------------------------------------------------------

    // repeated .raincom.apa.msgs.Vec2 corners = 3;
    int corners_size() const;
    void clear_corners();
    static const int kCornersFieldNumber = 3;
    ::raincom::apa::msgs::Vec2 *mutable_corners(int index);
    ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Vec2> *mutable_corners();
    const ::raincom::apa::msgs::Vec2 &corners(int index) const;
    ::raincom::apa::msgs::Vec2 *add_corners();
    const ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Vec2> &corners()
        const;

    // int32 id = 1;
    void clear_id();
    static const int kIdFieldNumber = 1;
    ::google::protobuf::int32 id() const;
    void set_id(::google::protobuf::int32 value);

    // .raincom.apa.msgs.Object.Clf clf = 2;
    void clear_clf();
    static const int kClfFieldNumber = 2;
    ::raincom::apa::msgs::Object_Clf clf() const;
    void set_clf(::raincom::apa::msgs::Object_Clf value);

    // bool available = 4;
    void clear_available();
    static const int kAvailableFieldNumber = 4;
    bool available() const;
    void set_available(bool value);

    // @@protoc_insertion_point(class_scope:raincom.apa.msgs.Object)
  private:
    ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
    ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Vec2> corners_;
    ::google::protobuf::int32 id_;
    int clf_;
    bool available_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    friend struct ::protobuf_apa_5fmsgs_2fobjects_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Objects : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:raincom.apa.msgs.Objects)
                                                    */
{
  public:
    Objects();
    virtual ~Objects();

    Objects(const Objects &from);

    inline Objects &operator=(const Objects &from)
    {
        CopyFrom(from);
        return *this;
    }
#if LANG_CXX11
    Objects(Objects &&from) noexcept : Objects() { *this = ::std::move(from); }

    inline Objects &operator=(Objects &&from) noexcept
    {
        if (GetArenaNoVirtual() == from.GetArenaNoVirtual())
        {
            if (this != &from)
                InternalSwap(&from);
        }
        else
        {
            CopyFrom(from);
        }
        return *this;
    }
#endif
    static const ::google::protobuf::Descriptor *descriptor();
    static const Objects &default_instance();

    static void InitAsDefaultInstance(); // FOR INTERNAL USE ONLY
    static inline const Objects *internal_default_instance()
    {
        return reinterpret_cast<const Objects *>(&_Objects_default_instance_);
    }
    static constexpr int kIndexInFileMessages = 1;

    void Swap(Objects *other);
    friend void swap(Objects &a, Objects &b) { a.Swap(&b); }

    // implements Message ----------------------------------------------

    inline Objects *New() const final { return CreateMaybeMessage<Objects>(NULL); }

    Objects *New(::google::protobuf::Arena *arena) const final
    {
        return CreateMaybeMessage<Objects>(arena);
    }
    void CopyFrom(const ::google::protobuf::Message &from) final;
    void MergeFrom(const ::google::protobuf::Message &from) final;
    void CopyFrom(const Objects &from);
    void MergeFrom(const Objects &from);
    void Clear() final;
    bool IsInitialized() const final;

    size_t ByteSizeLong() const final;
    bool MergePartialFromCodedStream(
        ::google::protobuf::io::CodedInputStream *input) final;
    void SerializeWithCachedSizes(
        ::google::protobuf::io::CodedOutputStream *output) const final;
    ::google::protobuf::uint8 *InternalSerializeWithCachedSizesToArray(
        bool deterministic, ::google::protobuf::uint8 *target) const final;
    int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
    void SharedCtor();
    void SharedDtor();
    void SetCachedSize(int size) const final;
    void InternalSwap(Objects *other);

  private:
    inline ::google::protobuf::Arena *GetArenaNoVirtual() const { return NULL; }
    inline void *MaybeArenaPtr() const { return NULL; }

  public:
    ::google::protobuf::Metadata GetMetadata() const final;

    // nested types ----------------------------------------------------

    // accessors -------------------------------------------------------

    // repeated .raincom.apa.msgs.Object objects = 2;
    int objects_size() const;
    void clear_objects();
    static const int kObjectsFieldNumber = 2;
    ::raincom::apa::msgs::Object *mutable_objects(int index);
    ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Object> *mutable_objects();
    const ::raincom::apa::msgs::Object &objects(int index) const;
    ::raincom::apa::msgs::Object *add_objects();
    const ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Object> &objects()
        const;

    // .raincom.apa.msgs.Header header = 1;
    bool has_header() const;
    void clear_header();
    static const int kHeaderFieldNumber = 1;

  private:
    const ::raincom::apa::msgs::Header &_internal_header() const;

  public:
    const ::raincom::apa::msgs::Header &header() const;
    ::raincom::apa::msgs::Header *release_header();
    ::raincom::apa::msgs::Header *mutable_header();
    void set_allocated_header(::raincom::apa::msgs::Header *header);

    // @@protoc_insertion_point(class_scope:raincom.apa.msgs.Objects)
  private:
    ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
    ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Object> objects_;
    ::raincom::apa::msgs::Header *header_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    friend struct ::protobuf_apa_5fmsgs_2fobjects_2eproto::TableStruct;
};
// ===================================================================

// ===================================================================

#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif // __GNUC__
// Object

// int32 id = 1;
inline void Object::clear_id() { id_ = 0; }
inline ::google::protobuf::int32 Object::id() const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Object.id)
    return id_;
}
inline void Object::set_id(::google::protobuf::int32 value)
{

    id_ = value;
    // @@protoc_insertion_point(field_set:raincom.apa.msgs.Object.id)
}

// .raincom.apa.msgs.Object.Clf clf = 2;
inline void Object::clear_clf() { clf_ = 0; }
inline ::raincom::apa::msgs::Object_Clf Object::clf() const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Object.clf)
    return static_cast<::raincom::apa::msgs::Object_Clf>(clf_);
}
inline void Object::set_clf(::raincom::apa::msgs::Object_Clf value)
{

    clf_ = value;
    // @@protoc_insertion_point(field_set:raincom.apa.msgs.Object.clf)
}

// repeated .raincom.apa.msgs.Vec2 corners = 3;
inline int Object::corners_size() const { return corners_.size(); }
inline ::raincom::apa::msgs::Vec2 *Object::mutable_corners(int index)
{
    // @@protoc_insertion_point(field_mutable:raincom.apa.msgs.Object.corners)
    return corners_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Vec2>
    *Object::mutable_corners()
{
    // @@protoc_insertion_point(field_mutable_list:raincom.apa.msgs.Object.corners)
    return &corners_;
}
inline const ::raincom::apa::msgs::Vec2 &Object::corners(int index) const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Object.corners)
    return corners_.Get(index);
}
inline ::raincom::apa::msgs::Vec2 *Object::add_corners()
{
    // @@protoc_insertion_point(field_add:raincom.apa.msgs.Object.corners)
    return corners_.Add();
}
inline const ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Vec2>
    &Object::corners() const
{
    // @@protoc_insertion_point(field_list:raincom.apa.msgs.Object.corners)
    return corners_;
}

// bool available = 4;
inline void Object::clear_available() { available_ = false; }
inline bool Object::available() const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Object.available)
    return available_;
}
inline void Object::set_available(bool value)
{

    available_ = value;
    // @@protoc_insertion_point(field_set:raincom.apa.msgs.Object.available)
}

// -------------------------------------------------------------------

// Objects

// .raincom.apa.msgs.Header header = 1;
inline bool Objects::has_header() const
{
    return this != internal_default_instance() && header_ != NULL;
}
inline const ::raincom::apa::msgs::Header &Objects::_internal_header() const
{
    return *header_;
}
inline const ::raincom::apa::msgs::Header &Objects::header() const
{
    const ::raincom::apa::msgs::Header *p = header_;
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Objects.header)
    return p != NULL ? *p
                     : *reinterpret_cast<const ::raincom::apa::msgs::Header *>(
                           &::raincom::apa::msgs::_Header_default_instance_);
}
inline ::raincom::apa::msgs::Header *Objects::release_header()
{
    // @@protoc_insertion_point(field_release:raincom.apa.msgs.Objects.header)

    ::raincom::apa::msgs::Header *temp = header_;
    header_                            = NULL;
    return temp;
}
inline ::raincom::apa::msgs::Header *Objects::mutable_header()
{

    if (header_ == NULL)
    {
        auto *p = CreateMaybeMessage<::raincom::apa::msgs::Header>(GetArenaNoVirtual());
        header_ = p;
    }
    // @@protoc_insertion_point(field_mutable:raincom.apa.msgs.Objects.header)
    return header_;
}
inline void Objects::set_allocated_header(::raincom::apa::msgs::Header *header)
{
    ::google::protobuf::Arena *message_arena = GetArenaNoVirtual();
    if (message_arena == NULL)
    {
        delete reinterpret_cast<::google::protobuf::MessageLite *>(header_);
    }
    if (header)
    {
        ::google::protobuf::Arena *submessage_arena = NULL;
        if (message_arena != submessage_arena)
        {
            header = ::google::protobuf::internal::GetOwnedMessage(message_arena, header,
                                                                   submessage_arena);
        }
    }
    else
    {
    }
    header_ = header;
    // @@protoc_insertion_point(field_set_allocated:raincom.apa.msgs.Objects.header)
}

// repeated .raincom.apa.msgs.Object objects = 2;
inline int Objects::objects_size() const { return objects_.size(); }
inline void Objects::clear_objects() { objects_.Clear(); }
inline ::raincom::apa::msgs::Object *Objects::mutable_objects(int index)
{
    // @@protoc_insertion_point(field_mutable:raincom.apa.msgs.Objects.objects)
    return objects_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Object>
    *Objects::mutable_objects()
{
    // @@protoc_insertion_point(field_mutable_list:raincom.apa.msgs.Objects.objects)
    return &objects_;
}
inline const ::raincom::apa::msgs::Object &Objects::objects(int index) const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Objects.objects)
    return objects_.Get(index);
}
inline ::raincom::apa::msgs::Object *Objects::add_objects()
{
    // @@protoc_insertion_point(field_add:raincom.apa.msgs.Objects.objects)
    return objects_.Add();
}
inline const ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Object>
    &Objects::objects() const
{
    // @@protoc_insertion_point(field_list:raincom.apa.msgs.Objects.objects)
    return objects_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif // __GNUC__
// -------------------------------------------------------------------

// @@protoc_insertion_point(namespace_scope)

} // namespace msgs
} // namespace apa
} // namespace raincom

namespace google
{
namespace protobuf
{

template <>
struct is_proto_enum<::raincom::apa::msgs::Object_Clf> : ::std::true_type
{
};
template <>
inline const EnumDescriptor *GetEnumDescriptor<::raincom::apa::msgs::Object_Clf>()
{
    return ::raincom::apa::msgs::Object_Clf_descriptor();
}

} // namespace protobuf
} // namespace google

// @@protoc_insertion_point(global_scope)

#endif // PROTOBUF_INCLUDED_apa_5fmsgs_2fobjects_2eproto
