// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apa_msgs/routing.proto

#ifndef PROTOBUF_INCLUDED_apa_5fmsgs_2frouting_2eproto
#define PROTOBUF_INCLUDED_apa_5fmsgs_2frouting_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h> // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "apa_msgs/common.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_apa_5fmsgs_2frouting_2eproto

namespace protobuf_apa_5fmsgs_2frouting_2eproto
{
// Internal implementation detail -- do not use these members.
struct TableStruct
{
    static const ::google::protobuf::internal::ParseTableField entries[];
    static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
    static const ::google::protobuf::internal::ParseTable schema[1];
    static const ::google::protobuf::internal::FieldMetadata field_metadata[];
    static const ::google::protobuf::internal::SerializationTable serialization_table[];
    static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
} // namespace protobuf_apa_5fmsgs_2frouting_2eproto
namespace raincom
{
namespace apa
{
namespace msgs
{
class Path;
class PathDefaultTypeInternal;
extern PathDefaultTypeInternal _Path_default_instance_;
} // namespace msgs
} // namespace apa
} // namespace raincom
namespace google
{
namespace protobuf
{
template <>
::raincom::apa::msgs::Path *Arena::CreateMaybeMessage<::raincom::apa::msgs::Path>(
    Arena *);
} // namespace protobuf
} // namespace google
namespace raincom
{
namespace apa
{
namespace msgs
{

// ===================================================================

class Path : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:raincom.apa.msgs.Path)
                                                 */
{
  public:
    Path();
    virtual ~Path();

    Path(const Path &from);

    inline Path &operator=(const Path &from)
    {
        CopyFrom(from);
        return *this;
    }
#if LANG_CXX11
    Path(Path &&from) noexcept : Path() { *this = ::std::move(from); }

    inline Path &operator=(Path &&from) noexcept
    {
        if (GetArenaNoVirtual() == from.GetArenaNoVirtual())
        {
            if (this != &from)
                InternalSwap(&from);
        }
        else
        {
            CopyFrom(from);
        }
        return *this;
    }
#endif
    static const ::google::protobuf::Descriptor *descriptor();
    static const Path &default_instance();

    static void InitAsDefaultInstance(); // FOR INTERNAL USE ONLY
    static inline const Path *internal_default_instance()
    {
        return reinterpret_cast<const Path *>(&_Path_default_instance_);
    }
    static constexpr int kIndexInFileMessages = 0;

    void Swap(Path *other);
    friend void swap(Path &a, Path &b) { a.Swap(&b); }

    // implements Message ----------------------------------------------

    inline Path *New() const final { return CreateMaybeMessage<Path>(NULL); }

    Path *New(::google::protobuf::Arena *arena) const final
    {
        return CreateMaybeMessage<Path>(arena);
    }
    void CopyFrom(const ::google::protobuf::Message &from) final;
    void MergeFrom(const ::google::protobuf::Message &from) final;
    void CopyFrom(const Path &from);
    void MergeFrom(const Path &from);
    void Clear() final;
    bool IsInitialized() const final;

    size_t ByteSizeLong() const final;
    bool MergePartialFromCodedStream(
        ::google::protobuf::io::CodedInputStream *input) final;
    void SerializeWithCachedSizes(
        ::google::protobuf::io::CodedOutputStream *output) const final;
    ::google::protobuf::uint8 *InternalSerializeWithCachedSizesToArray(
        bool deterministic, ::google::protobuf::uint8 *target) const final;
    int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
    void SharedCtor();
    void SharedDtor();
    void SetCachedSize(int size) const final;
    void InternalSwap(Path *other);

  private:
    inline ::google::protobuf::Arena *GetArenaNoVirtual() const { return NULL; }
    inline void *MaybeArenaPtr() const { return NULL; }

  public:
    ::google::protobuf::Metadata GetMetadata() const final;

    // nested types ----------------------------------------------------

    // accessors -------------------------------------------------------

    // repeated .raincom.apa.msgs.Pose trj = 2;
    int trj_size() const;
    void clear_trj();
    static const int kTrjFieldNumber = 2;
    ::raincom::apa::msgs::Pose *mutable_trj(int index);
    ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Pose> *mutable_trj();
    const ::raincom::apa::msgs::Pose &trj(int index) const;
    ::raincom::apa::msgs::Pose *add_trj();
    const ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Pose> &trj() const;

    // .raincom.apa.msgs.Header header = 1;
    bool has_header() const;
    void clear_header();
    static const int kHeaderFieldNumber = 1;

  private:
    const ::raincom::apa::msgs::Header &_internal_header() const;

  public:
    const ::raincom::apa::msgs::Header &header() const;
    ::raincom::apa::msgs::Header *release_header();
    ::raincom::apa::msgs::Header *mutable_header();
    void set_allocated_header(::raincom::apa::msgs::Header *header);

    // float length = 3;
    void clear_length();
    static const int kLengthFieldNumber = 3;
    float length() const;
    void set_length(float value);

    // @@protoc_insertion_point(class_scope:raincom.apa.msgs.Path)
  private:
    ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
    ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Pose> trj_;
    ::raincom::apa::msgs::Header *header_;
    float length_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    friend struct ::protobuf_apa_5fmsgs_2frouting_2eproto::TableStruct;
};
// ===================================================================

// ===================================================================

#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif // __GNUC__
// Path

// .raincom.apa.msgs.Header header = 1;
inline bool Path::has_header() const
{
    return this != internal_default_instance() && header_ != NULL;
}
inline const ::raincom::apa::msgs::Header &Path::_internal_header() const
{
    return *header_;
}
inline const ::raincom::apa::msgs::Header &Path::header() const
{
    const ::raincom::apa::msgs::Header *p = header_;
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Path.header)
    return p != NULL ? *p
                     : *reinterpret_cast<const ::raincom::apa::msgs::Header *>(
                           &::raincom::apa::msgs::_Header_default_instance_);
}
inline ::raincom::apa::msgs::Header *Path::release_header()
{
    // @@protoc_insertion_point(field_release:raincom.apa.msgs.Path.header)

    ::raincom::apa::msgs::Header *temp = header_;
    header_                            = NULL;
    return temp;
}
inline ::raincom::apa::msgs::Header *Path::mutable_header()
{

    if (header_ == NULL)
    {
        auto *p = CreateMaybeMessage<::raincom::apa::msgs::Header>(GetArenaNoVirtual());
        header_ = p;
    }
    // @@protoc_insertion_point(field_mutable:raincom.apa.msgs.Path.header)
    return header_;
}
inline void Path::set_allocated_header(::raincom::apa::msgs::Header *header)
{
    ::google::protobuf::Arena *message_arena = GetArenaNoVirtual();
    if (message_arena == NULL)
    {
        delete reinterpret_cast<::google::protobuf::MessageLite *>(header_);
    }
    if (header)
    {
        ::google::protobuf::Arena *submessage_arena = NULL;
        if (message_arena != submessage_arena)
        {
            header = ::google::protobuf::internal::GetOwnedMessage(message_arena, header,
                                                                   submessage_arena);
        }
    }
    else
    {
    }
    header_ = header;
    // @@protoc_insertion_point(field_set_allocated:raincom.apa.msgs.Path.header)
}

// repeated .raincom.apa.msgs.Pose trj = 2;
inline int Path::trj_size() const { return trj_.size(); }
inline ::raincom::apa::msgs::Pose *Path::mutable_trj(int index)
{
    // @@protoc_insertion_point(field_mutable:raincom.apa.msgs.Path.trj)
    return trj_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Pose>
    *Path::mutable_trj()
{
    // @@protoc_insertion_point(field_mutable_list:raincom.apa.msgs.Path.trj)
    return &trj_;
}
inline const ::raincom::apa::msgs::Pose &Path::trj(int index) const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Path.trj)
    return trj_.Get(index);
}
inline ::raincom::apa::msgs::Pose *Path::add_trj()
{
    // @@protoc_insertion_point(field_add:raincom.apa.msgs.Path.trj)
    return trj_.Add();
}
inline const ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Pose> &Path::trj()
    const
{
    // @@protoc_insertion_point(field_list:raincom.apa.msgs.Path.trj)
    return trj_;
}

// float length = 3;
inline void Path::clear_length() { length_ = 0; }
inline float Path::length() const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Path.length)
    return length_;
}
inline void Path::set_length(float value)
{

    length_ = value;
    // @@protoc_insertion_point(field_set:raincom.apa.msgs.Path.length)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif // __GNUC__

// @@protoc_insertion_point(namespace_scope)

} // namespace msgs
} // namespace apa
} // namespace raincom

// @@protoc_insertion_point(global_scope)

#endif // PROTOBUF_INCLUDED_apa_5fmsgs_2frouting_2eproto
