// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file MultiPolygonFrame.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_APA_MSGS_MSG_MULTIPOLYGONFRAME_H_
#define _FAST_DDS_GENERATED_APA_MSGS_MSG_MULTIPOLYGONFRAME_H_

#include "PolygonFrame.h"

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(MultiPolygonFrame_SOURCE)
#define MultiPolygonFrame_DllAPI __declspec( dllexport )
#else
#define MultiPolygonFrame_DllAPI __declspec( dllimport )
#endif // MultiPolygonFrame_SOURCE
#else
#define MultiPolygonFrame_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define MultiPolygonFrame_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


namespace apa_msgs {
    namespace msg {
        /*!
         * @brief This class represents the structure MultiPolygonFrame defined by the user in the IDL file.
         * @ingroup MULTIPOLYGONFRAME
         */
        class MultiPolygonFrame
        {
        public:

            /*!
             * @brief Default constructor.
             */
            eProsima_user_DllExport MultiPolygonFrame();

            /*!
             * @brief Default destructor.
             */
            eProsima_user_DllExport ~MultiPolygonFrame();

            /*!
             * @brief Copy constructor.
             * @param x Reference to the object apa_msgs::msg::MultiPolygonFrame that will be copied.
             */
            eProsima_user_DllExport MultiPolygonFrame(
                    const MultiPolygonFrame& x);

            /*!
             * @brief Move constructor.
             * @param x Reference to the object apa_msgs::msg::MultiPolygonFrame that will be copied.
             */
            eProsima_user_DllExport MultiPolygonFrame(
                    MultiPolygonFrame&& x);

            /*!
             * @brief Copy assignment.
             * @param x Reference to the object apa_msgs::msg::MultiPolygonFrame that will be copied.
             */
            eProsima_user_DllExport MultiPolygonFrame& operator =(
                    const MultiPolygonFrame& x);

            /*!
             * @brief Move assignment.
             * @param x Reference to the object apa_msgs::msg::MultiPolygonFrame that will be copied.
             */
            eProsima_user_DllExport MultiPolygonFrame& operator =(
                    MultiPolygonFrame&& x);

            /*!
             * @brief Comparison operator.
             * @param x apa_msgs::msg::MultiPolygonFrame object to compare.
             */
            eProsima_user_DllExport bool operator ==(
                    const MultiPolygonFrame& x) const;

            /*!
             * @brief Comparison operator.
             * @param x apa_msgs::msg::MultiPolygonFrame object to compare.
             */
            eProsima_user_DllExport bool operator !=(
                    const MultiPolygonFrame& x) const;

            /*!
             * @brief This function copies the value in member header
             * @param _header New value to be copied in member header
             */
            eProsima_user_DllExport void header(
                    const apa_msgs::msg::Header& _header);

            /*!
             * @brief This function moves the value in member header
             * @param _header New value to be moved in member header
             */
            eProsima_user_DllExport void header(
                    apa_msgs::msg::Header&& _header);

            /*!
             * @brief This function returns a constant reference to member header
             * @return Constant reference to member header
             */
            eProsima_user_DllExport const apa_msgs::msg::Header& header() const;

            /*!
             * @brief This function returns a reference to member header
             * @return Reference to member header
             */
            eProsima_user_DllExport apa_msgs::msg::Header& header();
            /*!
             * @brief This function copies the value in member polygon
             * @param _polygon New value to be copied in member polygon
             */
            eProsima_user_DllExport void polygon(
                    const std::vector<apa_msgs::msg::PolygonFrame>& _polygon);

            /*!
             * @brief This function moves the value in member polygon
             * @param _polygon New value to be moved in member polygon
             */
            eProsima_user_DllExport void polygon(
                    std::vector<apa_msgs::msg::PolygonFrame>&& _polygon);

            /*!
             * @brief This function returns a constant reference to member polygon
             * @return Constant reference to member polygon
             */
            eProsima_user_DllExport const std::vector<apa_msgs::msg::PolygonFrame>& polygon() const;

            /*!
             * @brief This function returns a reference to member polygon
             * @return Reference to member polygon
             */
            eProsima_user_DllExport std::vector<apa_msgs::msg::PolygonFrame>& polygon();

            /*!
             * @brief This function returns the maximum serialized size of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function returns the serialized size of a data depending on the buffer alignment.
             * @param data Data which is calculated its serialized size.
             * @param current_alignment Buffer alignment.
             * @return Serialized size.
             */
            eProsima_user_DllExport static size_t getCdrSerializedSize(
                    const apa_msgs::msg::MultiPolygonFrame& data,
                    size_t current_alignment = 0);


            /*!
             * @brief This function serializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serialize(
                    eprosima::fastcdr::Cdr& cdr) const;

            /*!
             * @brief This function deserializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void deserialize(
                    eprosima::fastcdr::Cdr& cdr);



            /*!
             * @brief This function returns the maximum serialized size of the Key of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function tells you if the Key has been defined for this type
             */
            eProsima_user_DllExport static bool isKeyDefined();

            /*!
             * @brief This function serializes the key members of an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serializeKey(
                    eprosima::fastcdr::Cdr& cdr) const;

        private:

            apa_msgs::msg::Header m_header;
            std::vector<apa_msgs::msg::PolygonFrame> m_polygon;
        };
    } // namespace msg
} // namespace apa_msgs

#endif // _FAST_DDS_GENERATED_APA_MSGS_MSG_MULTIPOLYGONFRAME_H_