// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file PolygonFrame.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_APA_MSGS_MSG_POLYGONFRAME_H_
#define _FAST_DDS_GENERATED_APA_MSGS_MSG_POLYGONFRAME_H_

#include "HeaderType.h"
#include "Pos2D.h"

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(PolygonFrame_SOURCE)
#define PolygonFrame_DllAPI __declspec( dllexport )
#else
#define PolygonFrame_DllAPI __declspec( dllimport )
#endif // PolygonFrame_SOURCE
#else
#define PolygonFrame_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define PolygonFrame_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


namespace apa_msgs {
    namespace msg {
        namespace PolygonTypeConst {
            const uint8_t POLYGON_UNKNOWN = 0;
            const uint8_t POLYGON_POINT = 1;
            const uint8_t POLYGON_LINE = 2;
            const uint8_t POLYGON_TRI = 3;
            const uint8_t POLYGON_QUAD = 4;
            const uint8_t POLYGON_POLY = 5;
            const uint8_t POLYGON_OPEN = 6;
            const uint8_t POLYGON_PARK_SOLT = 100;
            const uint8_t POLYGON_VEH_POS = 101;
            const uint8_t POLYGON_RESERVED_3 = 102;
            const uint8_t POLYGON_RESERVED_4 = 103;
            const uint8_t POLYGON_RESERVED_5 = 104;
            const uint8_t POLYGON_RESERVED_6 = 105;
        } // namespace PolygonTypeConst
        /*!
         * @brief This class represents the structure PolygonFrame defined by the user in the IDL file.
         * @ingroup POLYGONFRAME
         */
        class PolygonFrame
        {
        public:

            /*!
             * @brief Default constructor.
             */
            eProsima_user_DllExport PolygonFrame();

            /*!
             * @brief Default destructor.
             */
            eProsima_user_DllExport ~PolygonFrame();

            /*!
             * @brief Copy constructor.
             * @param x Reference to the object apa_msgs::msg::PolygonFrame that will be copied.
             */
            eProsima_user_DllExport PolygonFrame(
                    const PolygonFrame& x);

            /*!
             * @brief Move constructor.
             * @param x Reference to the object apa_msgs::msg::PolygonFrame that will be copied.
             */
            eProsima_user_DllExport PolygonFrame(
                    PolygonFrame&& x);

            /*!
             * @brief Copy assignment.
             * @param x Reference to the object apa_msgs::msg::PolygonFrame that will be copied.
             */
            eProsima_user_DllExport PolygonFrame& operator =(
                    const PolygonFrame& x);

            /*!
             * @brief Move assignment.
             * @param x Reference to the object apa_msgs::msg::PolygonFrame that will be copied.
             */
            eProsima_user_DllExport PolygonFrame& operator =(
                    PolygonFrame&& x);

            /*!
             * @brief Comparison operator.
             * @param x apa_msgs::msg::PolygonFrame object to compare.
             */
            eProsima_user_DllExport bool operator ==(
                    const PolygonFrame& x) const;

            /*!
             * @brief Comparison operator.
             * @param x apa_msgs::msg::PolygonFrame object to compare.
             */
            eProsima_user_DllExport bool operator !=(
                    const PolygonFrame& x) const;

            /*!
             * @brief This function copies the value in member header
             * @param _header New value to be copied in member header
             */
            eProsima_user_DllExport void header(
                    const apa_msgs::msg::Header& _header);

            /*!
             * @brief This function moves the value in member header
             * @param _header New value to be moved in member header
             */
            eProsima_user_DllExport void header(
                    apa_msgs::msg::Header&& _header);

            /*!
             * @brief This function returns a constant reference to member header
             * @return Constant reference to member header
             */
            eProsima_user_DllExport const apa_msgs::msg::Header& header() const;

            /*!
             * @brief This function returns a reference to member header
             * @return Reference to member header
             */
            eProsima_user_DllExport apa_msgs::msg::Header& header();
            /*!
             * @brief This function sets a value in member type
             * @param _type New value for member type
             */
            eProsima_user_DllExport void type(
                    uint8_t _type);

            /*!
             * @brief This function returns the value of member type
             * @return Value of member type
             */
            eProsima_user_DllExport uint8_t type() const;

            /*!
             * @brief This function returns a reference to member type
             * @return Reference to member type
             */
            eProsima_user_DllExport uint8_t& type();

            /*!
             * @brief This function copies the value in member points
             * @param _points New value to be copied in member points
             */
            eProsima_user_DllExport void points(
                    const std::vector<apa_msgs::msg::Pos2D>& _points);

            /*!
             * @brief This function moves the value in member points
             * @param _points New value to be moved in member points
             */
            eProsima_user_DllExport void points(
                    std::vector<apa_msgs::msg::Pos2D>&& _points);

            /*!
             * @brief This function returns a constant reference to member points
             * @return Constant reference to member points
             */
            eProsima_user_DllExport const std::vector<apa_msgs::msg::Pos2D>& points() const;

            /*!
             * @brief This function returns a reference to member points
             * @return Reference to member points
             */
            eProsima_user_DllExport std::vector<apa_msgs::msg::Pos2D>& points();
            /*!
             * @brief This function copies the value in member frame_info
             * @param _frame_info New value to be copied in member frame_info
             */
            eProsima_user_DllExport void frame_info(
                    const std::string& _frame_info);

            /*!
             * @brief This function moves the value in member frame_info
             * @param _frame_info New value to be moved in member frame_info
             */
            eProsima_user_DllExport void frame_info(
                    std::string&& _frame_info);

            /*!
             * @brief This function returns a constant reference to member frame_info
             * @return Constant reference to member frame_info
             */
            eProsima_user_DllExport const std::string& frame_info() const;

            /*!
             * @brief This function returns a reference to member frame_info
             * @return Reference to member frame_info
             */
            eProsima_user_DllExport std::string& frame_info();

            /*!
             * @brief This function returns the maximum serialized size of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function returns the serialized size of a data depending on the buffer alignment.
             * @param data Data which is calculated its serialized size.
             * @param current_alignment Buffer alignment.
             * @return Serialized size.
             */
            eProsima_user_DllExport static size_t getCdrSerializedSize(
                    const apa_msgs::msg::PolygonFrame& data,
                    size_t current_alignment = 0);


            /*!
             * @brief This function serializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serialize(
                    eprosima::fastcdr::Cdr& cdr) const;

            /*!
             * @brief This function deserializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void deserialize(
                    eprosima::fastcdr::Cdr& cdr);



            /*!
             * @brief This function returns the maximum serialized size of the Key of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function tells you if the Key has been defined for this type
             */
            eProsima_user_DllExport static bool isKeyDefined();

            /*!
             * @brief This function serializes the key members of an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serializeKey(
                    eprosima::fastcdr::Cdr& cdr) const;

        private:

            apa_msgs::msg::Header m_header;
            uint8_t m_type;
            std::vector<apa_msgs::msg::Pos2D> m_points;
            std::string m_frame_info;
        };
    } // namespace msg
} // namespace apa_msgs

#endif // _FAST_DDS_GENERATED_APA_MSGS_MSG_POLYGONFRAME_H_