// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file NavPosFramePub.cpp
 * This file contains the implementation of the publisher functions.
 *
 * This file was generated by the tool fastcdrgen.
 */

#include "NavPosFramePub.h"
#include "PolygonFramePubSubTypes.h"

#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/publisher/Publisher.hpp>
#include <fastdds/dds/publisher/qos/PublisherQos.hpp>
#include <fastdds/dds/publisher/DataWriter.hpp>
#include <fastdds/dds/publisher/qos/DataWriterQos.hpp>

#include <thread>
#include <chrono>
#include "Rte.h"
#include "Record_Log.h"

using namespace eprosima::fastdds::dds;

NavPosFramePub::NavPosFramePub()
    : participant_(nullptr),
      publisher_(nullptr),
      topic_(nullptr),
      writer_(nullptr),
      type_(new apa_msgs::msg::PolygonFramePubSubType())
{
}

NavPosFramePub::~NavPosFramePub()
{
    if (writer_ != nullptr)
    {
        publisher_->delete_datawriter(writer_);
    }
    if (publisher_ != nullptr)
    {
        participant_->delete_publisher(publisher_);
    }
    if (topic_ != nullptr)
    {
        participant_->delete_topic(topic_);
    }
    DomainParticipantFactory::get_instance()->delete_participant(participant_);
}

bool NavPosFramePub::init()
{
    /* Initialize data_ here */

    // CREATE THE PARTICIPANT
    DomainParticipantQos pqos;
    pqos.name("Participant_pub");
    participant_ = DomainParticipantFactory::get_instance()->create_participant(0, pqos);
    if (participant_ == nullptr)
    {
        return false;
    }

    // REGISTER THE TYPE
    type_.register_type(participant_);

    // CREATE THE PUBLISHER
    publisher_ = participant_->create_publisher(PUBLISHER_QOS_DEFAULT, nullptr);
    if (publisher_ == nullptr)
    {
        return false;
    }

    // CREATE THE TOPIC
    topic_ = participant_->create_topic("rt/nav_pos", type_.get_type_name(),
                                        TOPIC_QOS_DEFAULT);
    if (topic_ == nullptr)
    {
        return false;
    }

    // CREATE THE WRITER
    writer_ = publisher_->create_datawriter(topic_, DATAWRITER_QOS_DEFAULT, &listener_);
    if (writer_ == nullptr)
    {
        return false;
    }

    std::cout << "apa_msgs::msg::PolygonFrame DataWriter created." << std::endl;
    return true;
}

void NavPosFramePub::PubListener::on_publication_matched(
    eprosima::fastdds::dds::DataWriter *,
    const eprosima::fastdds::dds::PublicationMatchedStatus &info)
{
    if (info.current_count_change == 1)
    {
        matched = info.total_count;
        std::cout << "DataWriter matched." << std::endl;
    }
    else if (info.current_count_change == -1)
    {
        matched = info.total_count;
        std::cout << "DataWriter unmatched." << std::endl;
    }
    else
    {
        std::cout
            << info.current_count_change
            << " is not a valid value for PublicationMatchedStatus current count change"
            << std::endl;
    }
}

void NavPosFramePub::run()
{
    while (listener_.matched == 0)
    {
        std::this_thread::sleep_for(std::chrono::milliseconds(250)); // Sleep 250 ms
    }

    // Publication code
    apa_msgs::msg::PolygonFrame st;
    RD_PosStamp curPos;
    RTE_PK_Location_Get_CurPos_With_Timestamp(&curPos);
    // float pa[4] = {};
    // RTE_PK_Location_Get_CurPos(pa);
    // uint64_t System_time = RTE_BSW_Get_AbsStampMs();
    // log_warn("pa.x(%f),pa.y(%f),pa.phi(%f),pa.t(%lld)", pa[0], pa[1], pa[2],
    // System_time);
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    st.header().stamp() = (uint64_t)(ts.tv_sec) * 1'000'000'000ULL + ts.tv_nsec;
    st.points().clear();
    apa_msgs::msg::Pos2D pos;
    pos.x()   = curPos.pos[0];
    pos.y()   = curPos.pos[1];
    pos.phi() = curPos.pos[2];
    st.points().push_back(pos);
    // log_warn("pos.x(%f),pos.y(%f),pos.phi(%f),pos.t(%lld)", st.points()[0].x(),
    //          st.points()[0].y(), st.points()[0].phi(), st.header().stamp());

    writer_->write(&st);
}
