// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apa_msgs/common.proto

#ifndef PROTOBUF_INCLUDED_apa_5fmsgs_2fcommon_2eproto
#define PROTOBUF_INCLUDED_apa_5fmsgs_2fcommon_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h> // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_apa_5fmsgs_2fcommon_2eproto

namespace protobuf_apa_5fmsgs_2fcommon_2eproto
{
// Internal implementation detail -- do not use these members.
struct TableStruct
{
    static const ::google::protobuf::internal::ParseTableField entries[];
    static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
    static const ::google::protobuf::internal::ParseTable schema[3];
    static const ::google::protobuf::internal::FieldMetadata field_metadata[];
    static const ::google::protobuf::internal::SerializationTable serialization_table[];
    static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
} // namespace protobuf_apa_5fmsgs_2fcommon_2eproto
namespace raincom
{
namespace apa
{
namespace msgs
{
class Header;
class HeaderDefaultTypeInternal;
extern HeaderDefaultTypeInternal _Header_default_instance_;
class Vec2;
class Vec2DefaultTypeInternal;
extern Vec2DefaultTypeInternal _Vec2_default_instance_;
class Vec3;
class Vec3DefaultTypeInternal;
extern Vec3DefaultTypeInternal _Vec3_default_instance_;
} // namespace msgs
} // namespace apa
} // namespace raincom
namespace google
{
namespace protobuf
{
template <>
::raincom::apa::msgs::Header *Arena::CreateMaybeMessage<::raincom::apa::msgs::Header>(
    Arena *);
template <>
::raincom::apa::msgs::Vec2 *Arena::CreateMaybeMessage<::raincom::apa::msgs::Vec2>(
    Arena *);
template <>
::raincom::apa::msgs::Vec3 *Arena::CreateMaybeMessage<::raincom::apa::msgs::Vec3>(
    Arena *);
} // namespace protobuf
} // namespace google
namespace raincom
{
namespace apa
{
namespace msgs
{

enum TrackState
{
    INVALID                                 = 0,
    NEW                                     = 1,
    UPDATE                                  = 2,
    PREDICTED                               = 3,
    TrackState_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
    TrackState_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool TrackState_IsValid(int value);
const TrackState TrackState_MIN = INVALID;
const TrackState TrackState_MAX = PREDICTED;
const int TrackState_ARRAYSIZE  = TrackState_MAX + 1;

const ::google::protobuf::EnumDescriptor *TrackState_descriptor();
inline const ::std::string &TrackState_Name(TrackState value)
{
    return ::google::protobuf::internal::NameOfEnum(TrackState_descriptor(), value);
}
inline bool TrackState_Parse(const ::std::string &name, TrackState *value)
{
    return ::google::protobuf::internal::ParseNamedEnum<TrackState>(
        TrackState_descriptor(), name, value);
}
// ===================================================================

class Header : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:raincom.apa.msgs.Header)
                                                   */
{
  public:
    Header();
    virtual ~Header();

    Header(const Header &from);

    inline Header &operator=(const Header &from)
    {
        CopyFrom(from);
        return *this;
    }
#if LANG_CXX11
    Header(Header &&from) noexcept : Header() { *this = ::std::move(from); }

    inline Header &operator=(Header &&from) noexcept
    {
        if (GetArenaNoVirtual() == from.GetArenaNoVirtual())
        {
            if (this != &from)
                InternalSwap(&from);
        }
        else
        {
            CopyFrom(from);
        }
        return *this;
    }
#endif
    static const ::google::protobuf::Descriptor *descriptor();
    static const Header &default_instance();

    static void InitAsDefaultInstance(); // FOR INTERNAL USE ONLY
    static inline const Header *internal_default_instance()
    {
        return reinterpret_cast<const Header *>(&_Header_default_instance_);
    }
    static constexpr int kIndexInFileMessages = 0;

    void Swap(Header *other);
    friend void swap(Header &a, Header &b) { a.Swap(&b); }

    // implements Message ----------------------------------------------

    inline Header *New() const final { return CreateMaybeMessage<Header>(NULL); }

    Header *New(::google::protobuf::Arena *arena) const final
    {
        return CreateMaybeMessage<Header>(arena);
    }
    void CopyFrom(const ::google::protobuf::Message &from) final;
    void MergeFrom(const ::google::protobuf::Message &from) final;
    void CopyFrom(const Header &from);
    void MergeFrom(const Header &from);
    void Clear() final;
    bool IsInitialized() const final;

    size_t ByteSizeLong() const final;
    bool MergePartialFromCodedStream(
        ::google::protobuf::io::CodedInputStream *input) final;
    void SerializeWithCachedSizes(
        ::google::protobuf::io::CodedOutputStream *output) const final;
    ::google::protobuf::uint8 *InternalSerializeWithCachedSizesToArray(
        bool deterministic, ::google::protobuf::uint8 *target) const final;
    int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
    void SharedCtor();
    void SharedDtor();
    void SetCachedSize(int size) const final;
    void InternalSwap(Header *other);

  private:
    inline ::google::protobuf::Arena *GetArenaNoVirtual() const { return NULL; }
    inline void *MaybeArenaPtr() const { return NULL; }

  public:
    ::google::protobuf::Metadata GetMetadata() const final;

    // nested types ----------------------------------------------------

    // accessors -------------------------------------------------------

    // uint64 stamp = 1;
    void clear_stamp();
    static const int kStampFieldNumber = 1;
    ::google::protobuf::uint64 stamp() const;
    void set_stamp(::google::protobuf::uint64 value);

    // int32 id = 2;
    void clear_id();
    static const int kIdFieldNumber = 2;
    ::google::protobuf::int32 id() const;
    void set_id(::google::protobuf::int32 value);

    // @@protoc_insertion_point(class_scope:raincom.apa.msgs.Header)
  private:
    ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
    ::google::protobuf::uint64 stamp_;
    ::google::protobuf::int32 id_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    friend struct ::protobuf_apa_5fmsgs_2fcommon_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Vec2 : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:raincom.apa.msgs.Vec2)
                                                 */
{
  public:
    Vec2();
    virtual ~Vec2();

    Vec2(const Vec2 &from);

    inline Vec2 &operator=(const Vec2 &from)
    {
        CopyFrom(from);
        return *this;
    }
#if LANG_CXX11
    Vec2(Vec2 &&from) noexcept : Vec2() { *this = ::std::move(from); }

    inline Vec2 &operator=(Vec2 &&from) noexcept
    {
        if (GetArenaNoVirtual() == from.GetArenaNoVirtual())
        {
            if (this != &from)
                InternalSwap(&from);
        }
        else
        {
            CopyFrom(from);
        }
        return *this;
    }
#endif
    static const ::google::protobuf::Descriptor *descriptor();
    static const Vec2 &default_instance();

    static void InitAsDefaultInstance(); // FOR INTERNAL USE ONLY
    static inline const Vec2 *internal_default_instance()
    {
        return reinterpret_cast<const Vec2 *>(&_Vec2_default_instance_);
    }
    static constexpr int kIndexInFileMessages = 1;

    void Swap(Vec2 *other);
    friend void swap(Vec2 &a, Vec2 &b) { a.Swap(&b); }

    // implements Message ----------------------------------------------

    inline Vec2 *New() const final { return CreateMaybeMessage<Vec2>(NULL); }

    Vec2 *New(::google::protobuf::Arena *arena) const final
    {
        return CreateMaybeMessage<Vec2>(arena);
    }
    void CopyFrom(const ::google::protobuf::Message &from) final;
    void MergeFrom(const ::google::protobuf::Message &from) final;
    void CopyFrom(const Vec2 &from);
    void MergeFrom(const Vec2 &from);
    void Clear() final;
    bool IsInitialized() const final;

    size_t ByteSizeLong() const final;
    bool MergePartialFromCodedStream(
        ::google::protobuf::io::CodedInputStream *input) final;
    void SerializeWithCachedSizes(
        ::google::protobuf::io::CodedOutputStream *output) const final;
    ::google::protobuf::uint8 *InternalSerializeWithCachedSizesToArray(
        bool deterministic, ::google::protobuf::uint8 *target) const final;
    int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
    void SharedCtor();
    void SharedDtor();
    void SetCachedSize(int size) const final;
    void InternalSwap(Vec2 *other);

  private:
    inline ::google::protobuf::Arena *GetArenaNoVirtual() const { return NULL; }
    inline void *MaybeArenaPtr() const { return NULL; }

  public:
    ::google::protobuf::Metadata GetMetadata() const final;

    // nested types ----------------------------------------------------

    // accessors -------------------------------------------------------

    // float x = 1;
    void clear_x();
    static const int kXFieldNumber = 1;
    float x() const;
    void set_x(float value);

    // float y = 2;
    void clear_y();
    static const int kYFieldNumber = 2;
    float y() const;
    void set_y(float value);

    // @@protoc_insertion_point(class_scope:raincom.apa.msgs.Vec2)
  private:
    ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
    float x_;
    float y_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    friend struct ::protobuf_apa_5fmsgs_2fcommon_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Vec3 : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:raincom.apa.msgs.Vec3)
                                                 */
{
  public:
    Vec3();
    virtual ~Vec3();

    Vec3(const Vec3 &from);

    inline Vec3 &operator=(const Vec3 &from)
    {
        CopyFrom(from);
        return *this;
    }
#if LANG_CXX11
    Vec3(Vec3 &&from) noexcept : Vec3() { *this = ::std::move(from); }

    inline Vec3 &operator=(Vec3 &&from) noexcept
    {
        if (GetArenaNoVirtual() == from.GetArenaNoVirtual())
        {
            if (this != &from)
                InternalSwap(&from);
        }
        else
        {
            CopyFrom(from);
        }
        return *this;
    }
#endif
    static const ::google::protobuf::Descriptor *descriptor();
    static const Vec3 &default_instance();

    static void InitAsDefaultInstance(); // FOR INTERNAL USE ONLY
    static inline const Vec3 *internal_default_instance()
    {
        return reinterpret_cast<const Vec3 *>(&_Vec3_default_instance_);
    }
    static constexpr int kIndexInFileMessages = 2;

    void Swap(Vec3 *other);
    friend void swap(Vec3 &a, Vec3 &b) { a.Swap(&b); }

    // implements Message ----------------------------------------------

    inline Vec3 *New() const final { return CreateMaybeMessage<Vec3>(NULL); }

    Vec3 *New(::google::protobuf::Arena *arena) const final
    {
        return CreateMaybeMessage<Vec3>(arena);
    }
    void CopyFrom(const ::google::protobuf::Message &from) final;
    void MergeFrom(const ::google::protobuf::Message &from) final;
    void CopyFrom(const Vec3 &from);
    void MergeFrom(const Vec3 &from);
    void Clear() final;
    bool IsInitialized() const final;

    size_t ByteSizeLong() const final;
    bool MergePartialFromCodedStream(
        ::google::protobuf::io::CodedInputStream *input) final;
    void SerializeWithCachedSizes(
        ::google::protobuf::io::CodedOutputStream *output) const final;
    ::google::protobuf::uint8 *InternalSerializeWithCachedSizesToArray(
        bool deterministic, ::google::protobuf::uint8 *target) const final;
    int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
    void SharedCtor();
    void SharedDtor();
    void SetCachedSize(int size) const final;
    void InternalSwap(Vec3 *other);

  private:
    inline ::google::protobuf::Arena *GetArenaNoVirtual() const { return NULL; }
    inline void *MaybeArenaPtr() const { return NULL; }

  public:
    ::google::protobuf::Metadata GetMetadata() const final;

    // nested types ----------------------------------------------------

    // accessors -------------------------------------------------------

    // float x = 1;
    void clear_x();
    static const int kXFieldNumber = 1;
    float x() const;
    void set_x(float value);

    // float y = 2;
    void clear_y();
    static const int kYFieldNumber = 2;
    float y() const;
    void set_y(float value);

    // float z = 3;
    void clear_z();
    static const int kZFieldNumber = 3;
    float z() const;
    void set_z(float value);

    // @@protoc_insertion_point(class_scope:raincom.apa.msgs.Vec3)
  private:
    ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
    float x_;
    float y_;
    float z_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    friend struct ::protobuf_apa_5fmsgs_2fcommon_2eproto::TableStruct;
};
// ===================================================================

// ===================================================================

#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif // __GNUC__
// Header

// uint64 stamp = 1;
inline void Header::clear_stamp() { stamp_ = GOOGLE_ULONGLONG(0); }
inline ::google::protobuf::uint64 Header::stamp() const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Header.stamp)
    return stamp_;
}
inline void Header::set_stamp(::google::protobuf::uint64 value)
{

    stamp_ = value;
    // @@protoc_insertion_point(field_set:raincom.apa.msgs.Header.stamp)
}

// int32 id = 2;
inline void Header::clear_id() { id_ = 0; }
inline ::google::protobuf::int32 Header::id() const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Header.id)
    return id_;
}
inline void Header::set_id(::google::protobuf::int32 value)
{

    id_ = value;
    // @@protoc_insertion_point(field_set:raincom.apa.msgs.Header.id)
}

// -------------------------------------------------------------------

// Vec2

// float x = 1;
inline void Vec2::clear_x() { x_ = 0; }
inline float Vec2::x() const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Vec2.x)
    return x_;
}
inline void Vec2::set_x(float value)
{

    x_ = value;
    // @@protoc_insertion_point(field_set:raincom.apa.msgs.Vec2.x)
}

// float y = 2;
inline void Vec2::clear_y() { y_ = 0; }
inline float Vec2::y() const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Vec2.y)
    return y_;
}
inline void Vec2::set_y(float value)
{

    y_ = value;
    // @@protoc_insertion_point(field_set:raincom.apa.msgs.Vec2.y)
}

// -------------------------------------------------------------------

// Vec3

// float x = 1;
inline void Vec3::clear_x() { x_ = 0; }
inline float Vec3::x() const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Vec3.x)
    return x_;
}
inline void Vec3::set_x(float value)
{

    x_ = value;
    // @@protoc_insertion_point(field_set:raincom.apa.msgs.Vec3.x)
}

// float y = 2;
inline void Vec3::clear_y() { y_ = 0; }
inline float Vec3::y() const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Vec3.y)
    return y_;
}
inline void Vec3::set_y(float value)
{

    y_ = value;
    // @@protoc_insertion_point(field_set:raincom.apa.msgs.Vec3.y)
}

// float z = 3;
inline void Vec3::clear_z() { z_ = 0; }
inline float Vec3::z() const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Vec3.z)
    return z_;
}
inline void Vec3::set_z(float value)
{

    z_ = value;
    // @@protoc_insertion_point(field_set:raincom.apa.msgs.Vec3.z)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// @@protoc_insertion_point(namespace_scope)

} // namespace msgs
} // namespace apa
} // namespace raincom

namespace google
{
namespace protobuf
{

template <>
struct is_proto_enum<::raincom::apa::msgs::TrackState> : ::std::true_type
{
};
template <>
inline const EnumDescriptor *GetEnumDescriptor<::raincom::apa::msgs::TrackState>()
{
    return ::raincom::apa::msgs::TrackState_descriptor();
}

} // namespace protobuf
} // namespace google

// @@protoc_insertion_point(global_scope)

#endif // PROTOBUF_INCLUDED_apa_5fmsgs_2fcommon_2eproto
