// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apa_msgs/frame.proto

#ifndef PROTOBUF_INCLUDED_apa_5fmsgs_2fframe_2eproto
#define PROTOBUF_INCLUDED_apa_5fmsgs_2fframe_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h> // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "apa_msgs/common.pb.h"
#include "apa_msgs/slot.pb.h"
#include "apa_msgs/object.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_apa_5fmsgs_2fframe_2eproto

namespace protobuf_apa_5fmsgs_2fframe_2eproto
{
// Internal implementation detail -- do not use these members.
struct TableStruct
{
    static const ::google::protobuf::internal::ParseTableField entries[];
    static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
    static const ::google::protobuf::internal::ParseTable schema[1];
    static const ::google::protobuf::internal::FieldMetadata field_metadata[];
    static const ::google::protobuf::internal::SerializationTable serialization_table[];
    static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
} // namespace protobuf_apa_5fmsgs_2fframe_2eproto
namespace raincom
{
namespace apa
{
namespace msgs
{
class VisionFrame;
class VisionFrameDefaultTypeInternal;
extern VisionFrameDefaultTypeInternal _VisionFrame_default_instance_;
} // namespace msgs
} // namespace apa
} // namespace raincom
namespace google
{
namespace protobuf
{
template <>
::raincom::apa::msgs::VisionFrame *Arena::CreateMaybeMessage<
    ::raincom::apa::msgs::VisionFrame>(Arena *);
} // namespace protobuf
} // namespace google
namespace raincom
{
namespace apa
{
namespace msgs
{

enum VisionFrame_Source
{
    VisionFrame_Source_CAMERA = 0,
    VisionFrame_Source_FUSION = 1,
    VisionFrame_Source_VisionFrame_Source_INT_MIN_SENTINEL_DO_NOT_USE_ =
        ::google::protobuf::kint32min,
    VisionFrame_Source_VisionFrame_Source_INT_MAX_SENTINEL_DO_NOT_USE_ =
        ::google::protobuf::kint32max
};
bool VisionFrame_Source_IsValid(int value);
const VisionFrame_Source VisionFrame_Source_Source_MIN = VisionFrame_Source_CAMERA;
const VisionFrame_Source VisionFrame_Source_Source_MAX = VisionFrame_Source_FUSION;
const int VisionFrame_Source_Source_ARRAYSIZE = VisionFrame_Source_Source_MAX + 1;

const ::google::protobuf::EnumDescriptor *VisionFrame_Source_descriptor();
inline const ::std::string &VisionFrame_Source_Name(VisionFrame_Source value)
{
    return ::google::protobuf::internal::NameOfEnum(VisionFrame_Source_descriptor(),
                                                    value);
}
inline bool VisionFrame_Source_Parse(const ::std::string &name, VisionFrame_Source *value)
{
    return ::google::protobuf::internal::ParseNamedEnum<VisionFrame_Source>(
        VisionFrame_Source_descriptor(), name, value);
}
// ===================================================================

class VisionFrame : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:raincom.apa.msgs.VisionFrame)
                                                        */
{
  public:
    VisionFrame();
    virtual ~VisionFrame();

    VisionFrame(const VisionFrame &from);

    inline VisionFrame &operator=(const VisionFrame &from)
    {
        CopyFrom(from);
        return *this;
    }
#if LANG_CXX11
    VisionFrame(VisionFrame &&from) noexcept : VisionFrame()
    {
        *this = ::std::move(from);
    }

    inline VisionFrame &operator=(VisionFrame &&from) noexcept
    {
        if (GetArenaNoVirtual() == from.GetArenaNoVirtual())
        {
            if (this != &from)
                InternalSwap(&from);
        }
        else
        {
            CopyFrom(from);
        }
        return *this;
    }
#endif
    static const ::google::protobuf::Descriptor *descriptor();
    static const VisionFrame &default_instance();

    static void InitAsDefaultInstance(); // FOR INTERNAL USE ONLY
    static inline const VisionFrame *internal_default_instance()
    {
        return reinterpret_cast<const VisionFrame *>(&_VisionFrame_default_instance_);
    }
    static constexpr int kIndexInFileMessages = 0;

    void Swap(VisionFrame *other);
    friend void swap(VisionFrame &a, VisionFrame &b) { a.Swap(&b); }

    // implements Message ----------------------------------------------

    inline VisionFrame *New() const final
    {
        return CreateMaybeMessage<VisionFrame>(NULL);
    }

    VisionFrame *New(::google::protobuf::Arena *arena) const final
    {
        return CreateMaybeMessage<VisionFrame>(arena);
    }
    void CopyFrom(const ::google::protobuf::Message &from) final;
    void MergeFrom(const ::google::protobuf::Message &from) final;
    void CopyFrom(const VisionFrame &from);
    void MergeFrom(const VisionFrame &from);
    void Clear() final;
    bool IsInitialized() const final;

    size_t ByteSizeLong() const final;
    bool MergePartialFromCodedStream(
        ::google::protobuf::io::CodedInputStream *input) final;
    void SerializeWithCachedSizes(
        ::google::protobuf::io::CodedOutputStream *output) const final;
    ::google::protobuf::uint8 *InternalSerializeWithCachedSizesToArray(
        bool deterministic, ::google::protobuf::uint8 *target) const final;
    int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
    void SharedCtor();
    void SharedDtor();
    void SetCachedSize(int size) const final;
    void InternalSwap(VisionFrame *other);

  private:
    inline ::google::protobuf::Arena *GetArenaNoVirtual() const { return NULL; }
    inline void *MaybeArenaPtr() const { return NULL; }

  public:
    ::google::protobuf::Metadata GetMetadata() const final;

    // nested types ----------------------------------------------------

    typedef VisionFrame_Source Source;
    static const Source CAMERA = VisionFrame_Source_CAMERA;
    static const Source FUSION = VisionFrame_Source_FUSION;
    static inline bool Source_IsValid(int value)
    {
        return VisionFrame_Source_IsValid(value);
    }
    static const Source Source_MIN    = VisionFrame_Source_Source_MIN;
    static const Source Source_MAX    = VisionFrame_Source_Source_MAX;
    static const int Source_ARRAYSIZE = VisionFrame_Source_Source_ARRAYSIZE;
    static inline const ::google::protobuf::EnumDescriptor *Source_descriptor()
    {
        return VisionFrame_Source_descriptor();
    }
    static inline const ::std::string &Source_Name(Source value)
    {
        return VisionFrame_Source_Name(value);
    }
    static inline bool Source_Parse(const ::std::string &name, Source *value)
    {
        return VisionFrame_Source_Parse(name, value);
    }

    // accessors -------------------------------------------------------

    // repeated .raincom.apa.msgs.Object object_list = 2;
    int object_list_size() const;
    void clear_object_list();
    static const int kObjectListFieldNumber = 2;
    ::raincom::apa::msgs::Object *mutable_object_list(int index);
    ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Object>
        *mutable_object_list();
    const ::raincom::apa::msgs::Object &object_list(int index) const;
    ::raincom::apa::msgs::Object *add_object_list();
    const ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Object>
        &object_list() const;

    // repeated .raincom.apa.msgs.Slot slot_list = 3;
    int slot_list_size() const;
    void clear_slot_list();
    static const int kSlotListFieldNumber = 3;
    ::raincom::apa::msgs::Slot *mutable_slot_list(int index);
    ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Slot> *mutable_slot_list();
    const ::raincom::apa::msgs::Slot &slot_list(int index) const;
    ::raincom::apa::msgs::Slot *add_slot_list();
    const ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Slot> &slot_list()
        const;

    // .raincom.apa.msgs.Header header = 1;
    bool has_header() const;
    void clear_header();
    static const int kHeaderFieldNumber = 1;

  private:
    const ::raincom::apa::msgs::Header &_internal_header() const;

  public:
    const ::raincom::apa::msgs::Header &header() const;
    ::raincom::apa::msgs::Header *release_header();
    ::raincom::apa::msgs::Header *mutable_header();
    void set_allocated_header(::raincom::apa::msgs::Header *header);

    // .raincom.apa.msgs.VisionFrame.Source source = 4;
    void clear_source();
    static const int kSourceFieldNumber = 4;
    ::raincom::apa::msgs::VisionFrame_Source source() const;
    void set_source(::raincom::apa::msgs::VisionFrame_Source value);

    // @@protoc_insertion_point(class_scope:raincom.apa.msgs.VisionFrame)
  private:
    ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
    ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Object> object_list_;
    ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Slot> slot_list_;
    ::raincom::apa::msgs::Header *header_;
    int source_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    friend struct ::protobuf_apa_5fmsgs_2fframe_2eproto::TableStruct;
};
// ===================================================================

// ===================================================================

#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif // __GNUC__
// VisionFrame

// .raincom.apa.msgs.Header header = 1;
inline bool VisionFrame::has_header() const
{
    return this != internal_default_instance() && header_ != NULL;
}
inline const ::raincom::apa::msgs::Header &VisionFrame::_internal_header() const
{
    return *header_;
}
inline const ::raincom::apa::msgs::Header &VisionFrame::header() const
{
    const ::raincom::apa::msgs::Header *p = header_;
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.VisionFrame.header)
    return p != NULL ? *p
                     : *reinterpret_cast<const ::raincom::apa::msgs::Header *>(
                           &::raincom::apa::msgs::_Header_default_instance_);
}
inline ::raincom::apa::msgs::Header *VisionFrame::release_header()
{
    // @@protoc_insertion_point(field_release:raincom.apa.msgs.VisionFrame.header)

    ::raincom::apa::msgs::Header *temp = header_;
    header_                            = NULL;
    return temp;
}
inline ::raincom::apa::msgs::Header *VisionFrame::mutable_header()
{

    if (header_ == NULL)
    {
        auto *p = CreateMaybeMessage<::raincom::apa::msgs::Header>(GetArenaNoVirtual());
        header_ = p;
    }
    // @@protoc_insertion_point(field_mutable:raincom.apa.msgs.VisionFrame.header)
    return header_;
}
inline void VisionFrame::set_allocated_header(::raincom::apa::msgs::Header *header)
{
    ::google::protobuf::Arena *message_arena = GetArenaNoVirtual();
    if (message_arena == NULL)
    {
        delete reinterpret_cast<::google::protobuf::MessageLite *>(header_);
    }
    if (header)
    {
        ::google::protobuf::Arena *submessage_arena = NULL;
        if (message_arena != submessage_arena)
        {
            header = ::google::protobuf::internal::GetOwnedMessage(message_arena, header,
                                                                   submessage_arena);
        }
    }
    else
    {
    }
    header_ = header;
    // @@protoc_insertion_point(field_set_allocated:raincom.apa.msgs.VisionFrame.header)
}

// repeated .raincom.apa.msgs.Object object_list = 2;
inline int VisionFrame::object_list_size() const { return object_list_.size(); }
inline ::raincom::apa::msgs::Object *VisionFrame::mutable_object_list(int index)
{
    // @@protoc_insertion_point(field_mutable:raincom.apa.msgs.VisionFrame.object_list)
    return object_list_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Object>
    *VisionFrame::mutable_object_list()
{
    // @@protoc_insertion_point(field_mutable_list:raincom.apa.msgs.VisionFrame.object_list)
    return &object_list_;
}
inline const ::raincom::apa::msgs::Object &VisionFrame::object_list(int index) const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.VisionFrame.object_list)
    return object_list_.Get(index);
}
inline ::raincom::apa::msgs::Object *VisionFrame::add_object_list()
{
    // @@protoc_insertion_point(field_add:raincom.apa.msgs.VisionFrame.object_list)
    return object_list_.Add();
}
inline const ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Object>
    &VisionFrame::object_list() const
{
    // @@protoc_insertion_point(field_list:raincom.apa.msgs.VisionFrame.object_list)
    return object_list_;
}

// repeated .raincom.apa.msgs.Slot slot_list = 3;
inline int VisionFrame::slot_list_size() const { return slot_list_.size(); }
inline ::raincom::apa::msgs::Slot *VisionFrame::mutable_slot_list(int index)
{
    // @@protoc_insertion_point(field_mutable:raincom.apa.msgs.VisionFrame.slot_list)
    return slot_list_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Slot>
    *VisionFrame::mutable_slot_list()
{
    // @@protoc_insertion_point(field_mutable_list:raincom.apa.msgs.VisionFrame.slot_list)
    return &slot_list_;
}
inline const ::raincom::apa::msgs::Slot &VisionFrame::slot_list(int index) const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.VisionFrame.slot_list)
    return slot_list_.Get(index);
}
inline ::raincom::apa::msgs::Slot *VisionFrame::add_slot_list()
{
    // @@protoc_insertion_point(field_add:raincom.apa.msgs.VisionFrame.slot_list)
    return slot_list_.Add();
}
inline const ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Slot>
    &VisionFrame::slot_list() const
{
    // @@protoc_insertion_point(field_list:raincom.apa.msgs.VisionFrame.slot_list)
    return slot_list_;
}

// .raincom.apa.msgs.VisionFrame.Source source = 4;
inline void VisionFrame::clear_source() { source_ = 0; }
inline ::raincom::apa::msgs::VisionFrame_Source VisionFrame::source() const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.VisionFrame.source)
    return static_cast<::raincom::apa::msgs::VisionFrame_Source>(source_);
}
inline void VisionFrame::set_source(::raincom::apa::msgs::VisionFrame_Source value)
{

    source_ = value;
    // @@protoc_insertion_point(field_set:raincom.apa.msgs.VisionFrame.source)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif // __GNUC__

// @@protoc_insertion_point(namespace_scope)

} // namespace msgs
} // namespace apa
} // namespace raincom

namespace google
{
namespace protobuf
{

template <>
struct is_proto_enum<::raincom::apa::msgs::VisionFrame_Source> : ::std::true_type
{
};
template <>
inline const EnumDescriptor *GetEnumDescriptor<::raincom::apa::msgs::VisionFrame_Source>()
{
    return ::raincom::apa::msgs::VisionFrame_Source_descriptor();
}

} // namespace protobuf
} // namespace google

// @@protoc_insertion_point(global_scope)

#endif // PROTOBUF_INCLUDED_apa_5fmsgs_2fframe_2eproto
