// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apa_msgs/object.proto

#ifndef PROTOBUF_INCLUDED_apa_5fmsgs_2fobject_2eproto
#define PROTOBUF_INCLUDED_apa_5fmsgs_2fobject_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h> // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "apa_msgs/common.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_apa_5fmsgs_2fobject_2eproto

namespace protobuf_apa_5fmsgs_2fobject_2eproto
{
// Internal implementation detail -- do not use these members.
struct TableStruct
{
    static const ::google::protobuf::internal::ParseTableField entries[];
    static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
    static const ::google::protobuf::internal::ParseTable schema[1];
    static const ::google::protobuf::internal::FieldMetadata field_metadata[];
    static const ::google::protobuf::internal::SerializationTable serialization_table[];
    static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
} // namespace protobuf_apa_5fmsgs_2fobject_2eproto
namespace raincom
{
namespace apa
{
namespace msgs
{
class Object;
class ObjectDefaultTypeInternal;
extern ObjectDefaultTypeInternal _Object_default_instance_;
} // namespace msgs
} // namespace apa
} // namespace raincom
namespace google
{
namespace protobuf
{
template <>
::raincom::apa::msgs::Object *Arena::CreateMaybeMessage<::raincom::apa::msgs::Object>(
    Arena *);
} // namespace protobuf
} // namespace google
namespace raincom
{
namespace apa
{
namespace msgs
{

enum Object_Sensor
{
    Object_Sensor_FRONT = 0,
    Object_Sensor_RIGHT = 1,
    Object_Sensor_BACK  = 2,
    Object_Sensor_LEFT  = 3,
    Object_Sensor_BEV   = 4,
    Object_Sensor_Object_Sensor_INT_MIN_SENTINEL_DO_NOT_USE_ =
        ::google::protobuf::kint32min,
    Object_Sensor_Object_Sensor_INT_MAX_SENTINEL_DO_NOT_USE_ =
        ::google::protobuf::kint32max
};
bool Object_Sensor_IsValid(int value);
const Object_Sensor Object_Sensor_Sensor_MIN = Object_Sensor_FRONT;
const Object_Sensor Object_Sensor_Sensor_MAX = Object_Sensor_BEV;
const int Object_Sensor_Sensor_ARRAYSIZE     = Object_Sensor_Sensor_MAX + 1;

const ::google::protobuf::EnumDescriptor *Object_Sensor_descriptor();
inline const ::std::string &Object_Sensor_Name(Object_Sensor value)
{
    return ::google::protobuf::internal::NameOfEnum(Object_Sensor_descriptor(), value);
}
inline bool Object_Sensor_Parse(const ::std::string &name, Object_Sensor *value)
{
    return ::google::protobuf::internal::ParseNamedEnum<Object_Sensor>(
        Object_Sensor_descriptor(), name, value);
}
enum Object_Clf
{
    Object_Clf_UNKNOWN                                 = 0,
    Object_Clf_SLB                                     = 1,
    Object_Clf_CONE                                    = 2,
    Object_Clf_PL_CLOSED                               = 3,
    Object_Clf_PL_OPENED                               = 4,
    Object_Clf_OPLB_R                                  = 5,
    Object_Clf_OPLB_I                                  = 6,
    Object_Clf_HANDICAP                                = 7,
    Object_Clf_PVC                                     = 8,
    Object_Clf_CARTON                                  = 9,
    Object_Clf_CHAIR                                   = 10,
    Object_Clf_PEDSTRAIN                               = 11,
    Object_Clf_BUCKET                                  = 12,
    Object_Clf_E_BIKE                                  = 13,
    Object_Clf_STOP_SIGN                               = 14,
    Object_Clf_CHARGING_STOP                           = 15,
    Object_Clf_DECEL_STRIP                             = 16,
    Object_Clf_BUMPER                                  = 17,
    Object_Clf_FENCE                                   = 18,
    Object_Clf_WHEEL_CHAIR                             = 19,
    Object_Clf_FIRE_KIT                                = 20,
    Object_Clf_Object_Clf_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
    Object_Clf_Object_Clf_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Object_Clf_IsValid(int value);
const Object_Clf Object_Clf_Clf_MIN = Object_Clf_UNKNOWN;
const Object_Clf Object_Clf_Clf_MAX = Object_Clf_FIRE_KIT;
const int Object_Clf_Clf_ARRAYSIZE  = Object_Clf_Clf_MAX + 1;

const ::google::protobuf::EnumDescriptor *Object_Clf_descriptor();
inline const ::std::string &Object_Clf_Name(Object_Clf value)
{
    return ::google::protobuf::internal::NameOfEnum(Object_Clf_descriptor(), value);
}
inline bool Object_Clf_Parse(const ::std::string &name, Object_Clf *value)
{
    return ::google::protobuf::internal::ParseNamedEnum<Object_Clf>(
        Object_Clf_descriptor(), name, value);
}
// ===================================================================

class Object : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:raincom.apa.msgs.Object)
                                                   */
{
  public:
    Object();
    virtual ~Object();

    Object(const Object &from);

    inline Object &operator=(const Object &from)
    {
        CopyFrom(from);
        return *this;
    }
#if LANG_CXX11
    Object(Object &&from) noexcept : Object() { *this = ::std::move(from); }

    inline Object &operator=(Object &&from) noexcept
    {
        if (GetArenaNoVirtual() == from.GetArenaNoVirtual())
        {
            if (this != &from)
                InternalSwap(&from);
        }
        else
        {
            CopyFrom(from);
        }
        return *this;
    }
#endif
    static const ::google::protobuf::Descriptor *descriptor();
    static const Object &default_instance();

    static void InitAsDefaultInstance(); // FOR INTERNAL USE ONLY
    static inline const Object *internal_default_instance()
    {
        return reinterpret_cast<const Object *>(&_Object_default_instance_);
    }
    static constexpr int kIndexInFileMessages = 0;

    void Swap(Object *other);
    friend void swap(Object &a, Object &b) { a.Swap(&b); }

    // implements Message ----------------------------------------------

    inline Object *New() const final { return CreateMaybeMessage<Object>(NULL); }

    Object *New(::google::protobuf::Arena *arena) const final
    {
        return CreateMaybeMessage<Object>(arena);
    }
    void CopyFrom(const ::google::protobuf::Message &from) final;
    void MergeFrom(const ::google::protobuf::Message &from) final;
    void CopyFrom(const Object &from);
    void MergeFrom(const Object &from);
    void Clear() final;
    bool IsInitialized() const final;

    size_t ByteSizeLong() const final;
    bool MergePartialFromCodedStream(
        ::google::protobuf::io::CodedInputStream *input) final;
    void SerializeWithCachedSizes(
        ::google::protobuf::io::CodedOutputStream *output) const final;
    ::google::protobuf::uint8 *InternalSerializeWithCachedSizesToArray(
        bool deterministic, ::google::protobuf::uint8 *target) const final;
    int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
    void SharedCtor();
    void SharedDtor();
    void SetCachedSize(int size) const final;
    void InternalSwap(Object *other);

  private:
    inline ::google::protobuf::Arena *GetArenaNoVirtual() const { return NULL; }
    inline void *MaybeArenaPtr() const { return NULL; }

  public:
    ::google::protobuf::Metadata GetMetadata() const final;

    // nested types ----------------------------------------------------

    typedef Object_Sensor Sensor;
    static const Sensor FRONT = Object_Sensor_FRONT;
    static const Sensor RIGHT = Object_Sensor_RIGHT;
    static const Sensor BACK  = Object_Sensor_BACK;
    static const Sensor LEFT  = Object_Sensor_LEFT;
    static const Sensor BEV   = Object_Sensor_BEV;
    static inline bool Sensor_IsValid(int value) { return Object_Sensor_IsValid(value); }
    static const Sensor Sensor_MIN    = Object_Sensor_Sensor_MIN;
    static const Sensor Sensor_MAX    = Object_Sensor_Sensor_MAX;
    static const int Sensor_ARRAYSIZE = Object_Sensor_Sensor_ARRAYSIZE;
    static inline const ::google::protobuf::EnumDescriptor *Sensor_descriptor()
    {
        return Object_Sensor_descriptor();
    }
    static inline const ::std::string &Sensor_Name(Sensor value)
    {
        return Object_Sensor_Name(value);
    }
    static inline bool Sensor_Parse(const ::std::string &name, Sensor *value)
    {
        return Object_Sensor_Parse(name, value);
    }

    typedef Object_Clf Clf;
    static const Clf UNKNOWN       = Object_Clf_UNKNOWN;
    static const Clf SLB           = Object_Clf_SLB;
    static const Clf CONE          = Object_Clf_CONE;
    static const Clf PL_CLOSED     = Object_Clf_PL_CLOSED;
    static const Clf PL_OPENED     = Object_Clf_PL_OPENED;
    static const Clf OPLB_R        = Object_Clf_OPLB_R;
    static const Clf OPLB_I        = Object_Clf_OPLB_I;
    static const Clf HANDICAP      = Object_Clf_HANDICAP;
    static const Clf PVC           = Object_Clf_PVC;
    static const Clf CARTON        = Object_Clf_CARTON;
    static const Clf CHAIR         = Object_Clf_CHAIR;
    static const Clf PEDSTRAIN     = Object_Clf_PEDSTRAIN;
    static const Clf BUCKET        = Object_Clf_BUCKET;
    static const Clf E_BIKE        = Object_Clf_E_BIKE;
    static const Clf STOP_SIGN     = Object_Clf_STOP_SIGN;
    static const Clf CHARGING_STOP = Object_Clf_CHARGING_STOP;
    static const Clf DECEL_STRIP   = Object_Clf_DECEL_STRIP;
    static const Clf BUMPER        = Object_Clf_BUMPER;
    static const Clf FENCE         = Object_Clf_FENCE;
    static const Clf WHEEL_CHAIR   = Object_Clf_WHEEL_CHAIR;
    static const Clf FIRE_KIT      = Object_Clf_FIRE_KIT;
    static inline bool Clf_IsValid(int value) { return Object_Clf_IsValid(value); }
    static const Clf Clf_MIN       = Object_Clf_Clf_MIN;
    static const Clf Clf_MAX       = Object_Clf_Clf_MAX;
    static const int Clf_ARRAYSIZE = Object_Clf_Clf_ARRAYSIZE;
    static inline const ::google::protobuf::EnumDescriptor *Clf_descriptor()
    {
        return Object_Clf_descriptor();
    }
    static inline const ::std::string &Clf_Name(Clf value)
    {
        return Object_Clf_Name(value);
    }
    static inline bool Clf_Parse(const ::std::string &name, Clf *value)
    {
        return Object_Clf_Parse(name, value);
    }

    // accessors -------------------------------------------------------

    // repeated int32 ref_slots = 6;
    int ref_slots_size() const;
    void clear_ref_slots();
    static const int kRefSlotsFieldNumber = 6;
    ::google::protobuf::int32 ref_slots(int index) const;
    void set_ref_slots(int index, ::google::protobuf::int32 value);
    void add_ref_slots(::google::protobuf::int32 value);
    const ::google::protobuf::RepeatedField<::google::protobuf::int32> &ref_slots() const;
    ::google::protobuf::RepeatedField<::google::protobuf::int32> *mutable_ref_slots();

    // repeated bool shape_valid = 8;
    int shape_valid_size() const;
    void clear_shape_valid();
    static const int kShapeValidFieldNumber = 8;
    bool shape_valid(int index) const;
    void set_shape_valid(int index, bool value);
    void add_shape_valid(bool value);
    const ::google::protobuf::RepeatedField<bool> &shape_valid() const;
    ::google::protobuf::RepeatedField<bool> *mutable_shape_valid();

    // repeated .raincom.apa.msgs.Vec2 corners = 20;
    int corners_size() const;
    void clear_corners();
    static const int kCornersFieldNumber = 20;
    ::raincom::apa::msgs::Vec2 *mutable_corners(int index);
    ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Vec2> *mutable_corners();
    const ::raincom::apa::msgs::Vec2 &corners(int index) const;
    ::raincom::apa::msgs::Vec2 *add_corners();
    const ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Vec2> &corners()
        const;

    // repeated bool corners_valid = 21;
    int corners_valid_size() const;
    void clear_corners_valid();
    static const int kCornersValidFieldNumber = 21;
    bool corners_valid(int index) const;
    void set_corners_valid(int index, bool value);
    void add_corners_valid(bool value);
    const ::google::protobuf::RepeatedField<bool> &corners_valid() const;
    ::google::protobuf::RepeatedField<bool> *mutable_corners_valid();

    // repeated .raincom.apa.msgs.Vec2 corners_var = 22;
    int corners_var_size() const;
    void clear_corners_var();
    static const int kCornersVarFieldNumber = 22;
    ::raincom::apa::msgs::Vec2 *mutable_corners_var(int index);
    ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Vec2>
        *mutable_corners_var();
    const ::raincom::apa::msgs::Vec2 &corners_var(int index) const;
    ::raincom::apa::msgs::Vec2 *add_corners_var();
    const ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Vec2> &corners_var()
        const;

    // repeated .raincom.apa.msgs.Vec2 reliable_corners = 23;
    int reliable_corners_size() const;
    void clear_reliable_corners();
    static const int kReliableCornersFieldNumber = 23;
    ::raincom::apa::msgs::Vec2 *mutable_reliable_corners(int index);
    ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Vec2>
        *mutable_reliable_corners();
    const ::raincom::apa::msgs::Vec2 &reliable_corners(int index) const;
    ::raincom::apa::msgs::Vec2 *add_reliable_corners();
    const ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Vec2>
        &reliable_corners() const;

    // .raincom.apa.msgs.Header header = 1;
    bool has_header() const;
    void clear_header();
    static const int kHeaderFieldNumber = 1;

  private:
    const ::raincom::apa::msgs::Header &_internal_header() const;

  public:
    const ::raincom::apa::msgs::Header &header() const;
    ::raincom::apa::msgs::Header *release_header();
    ::raincom::apa::msgs::Header *mutable_header();
    void set_allocated_header(::raincom::apa::msgs::Header *header);

    // .raincom.apa.msgs.Vec3 shape = 7;
    bool has_shape() const;
    void clear_shape();
    static const int kShapeFieldNumber = 7;

  private:
    const ::raincom::apa::msgs::Vec3 &_internal_shape() const;

  public:
    const ::raincom::apa::msgs::Vec3 &shape() const;
    ::raincom::apa::msgs::Vec3 *release_shape();
    ::raincom::apa::msgs::Vec3 *mutable_shape();
    void set_allocated_shape(::raincom::apa::msgs::Vec3 *shape);

    // .raincom.apa.msgs.Vec3 shape_var = 9;
    bool has_shape_var() const;
    void clear_shape_var();
    static const int kShapeVarFieldNumber = 9;

  private:
    const ::raincom::apa::msgs::Vec3 &_internal_shape_var() const;

  public:
    const ::raincom::apa::msgs::Vec3 &shape_var() const;
    ::raincom::apa::msgs::Vec3 *release_shape_var();
    ::raincom::apa::msgs::Vec3 *mutable_shape_var();
    void set_allocated_shape_var(::raincom::apa::msgs::Vec3 *shape_var);

    // .raincom.apa.msgs.Vec2 nearest = 14;
    bool has_nearest() const;
    void clear_nearest();
    static const int kNearestFieldNumber = 14;

  private:
    const ::raincom::apa::msgs::Vec2 &_internal_nearest() const;

  public:
    const ::raincom::apa::msgs::Vec2 &nearest() const;
    ::raincom::apa::msgs::Vec2 *release_nearest();
    ::raincom::apa::msgs::Vec2 *mutable_nearest();
    void set_allocated_nearest(::raincom::apa::msgs::Vec2 *nearest);

    // .raincom.apa.msgs.Vec2 nearest_var = 16;
    bool has_nearest_var() const;
    void clear_nearest_var();
    static const int kNearestVarFieldNumber = 16;

  private:
    const ::raincom::apa::msgs::Vec2 &_internal_nearest_var() const;

  public:
    const ::raincom::apa::msgs::Vec2 &nearest_var() const;
    ::raincom::apa::msgs::Vec2 *release_nearest_var();
    ::raincom::apa::msgs::Vec2 *mutable_nearest_var();
    void set_allocated_nearest_var(::raincom::apa::msgs::Vec2 *nearest_var);

    // .raincom.apa.msgs.Vec2 center = 17;
    bool has_center() const;
    void clear_center();
    static const int kCenterFieldNumber = 17;

  private:
    const ::raincom::apa::msgs::Vec2 &_internal_center() const;

  public:
    const ::raincom::apa::msgs::Vec2 &center() const;
    ::raincom::apa::msgs::Vec2 *release_center();
    ::raincom::apa::msgs::Vec2 *mutable_center();
    void set_allocated_center(::raincom::apa::msgs::Vec2 *center);

    // .raincom.apa.msgs.Vec2 center_var = 19;
    bool has_center_var() const;
    void clear_center_var();
    static const int kCenterVarFieldNumber = 19;

  private:
    const ::raincom::apa::msgs::Vec2 &_internal_center_var() const;

  public:
    const ::raincom::apa::msgs::Vec2 &center_var() const;
    ::raincom::apa::msgs::Vec2 *release_center_var();
    ::raincom::apa::msgs::Vec2 *mutable_center_var();
    void set_allocated_center_var(::raincom::apa::msgs::Vec2 *center_var);

    // float conf = 2;
    void clear_conf();
    static const int kConfFieldNumber = 2;
    float conf() const;
    void set_conf(float value);

    // int32 age = 3;
    void clear_age();
    static const int kAgeFieldNumber = 3;
    ::google::protobuf::int32 age() const;
    void set_age(::google::protobuf::int32 value);

    // .raincom.apa.msgs.Object.Sensor sensor = 4;
    void clear_sensor();
    static const int kSensorFieldNumber = 4;
    ::raincom::apa::msgs::Object_Sensor sensor() const;
    void set_sensor(::raincom::apa::msgs::Object_Sensor value);

    // .raincom.apa.msgs.TrackState track_state = 5;
    void clear_track_state();
    static const int kTrackStateFieldNumber = 5;
    ::raincom::apa::msgs::TrackState track_state() const;
    void set_track_state(::raincom::apa::msgs::TrackState value);

    // float ori = 10;
    void clear_ori();
    static const int kOriFieldNumber = 10;
    float ori() const;
    void set_ori(float value);

    // float ori_var = 11;
    void clear_ori_var();
    static const int kOriVarFieldNumber = 11;
    float ori_var() const;
    void set_ori_var(float value);

    // .raincom.apa.msgs.Object.Clf clf = 12;
    void clear_clf();
    static const int kClfFieldNumber = 12;
    ::raincom::apa::msgs::Object_Clf clf() const;
    void set_clf(::raincom::apa::msgs::Object_Clf value);

    // float clf_conf = 13;
    void clear_clf_conf();
    static const int kClfConfFieldNumber = 13;
    float clf_conf() const;
    void set_clf_conf(float value);

    // bool nearest_valid = 15;
    void clear_nearest_valid();
    static const int kNearestValidFieldNumber = 15;
    bool nearest_valid() const;
    void set_nearest_valid(bool value);

    // bool center_valid = 18;
    void clear_center_valid();
    static const int kCenterValidFieldNumber = 18;
    bool center_valid() const;
    void set_center_valid(bool value);

    // @@protoc_insertion_point(class_scope:raincom.apa.msgs.Object)
  private:
    ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
    ::google::protobuf::RepeatedField<::google::protobuf::int32> ref_slots_;
    mutable int _ref_slots_cached_byte_size_;
    ::google::protobuf::RepeatedField<bool> shape_valid_;
    mutable int _shape_valid_cached_byte_size_;
    ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Vec2> corners_;
    ::google::protobuf::RepeatedField<bool> corners_valid_;
    mutable int _corners_valid_cached_byte_size_;
    ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Vec2> corners_var_;
    ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Vec2> reliable_corners_;
    ::raincom::apa::msgs::Header *header_;
    ::raincom::apa::msgs::Vec3 *shape_;
    ::raincom::apa::msgs::Vec3 *shape_var_;
    ::raincom::apa::msgs::Vec2 *nearest_;
    ::raincom::apa::msgs::Vec2 *nearest_var_;
    ::raincom::apa::msgs::Vec2 *center_;
    ::raincom::apa::msgs::Vec2 *center_var_;
    float conf_;
    ::google::protobuf::int32 age_;
    int sensor_;
    int track_state_;
    float ori_;
    float ori_var_;
    int clf_;
    float clf_conf_;
    bool nearest_valid_;
    bool center_valid_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    friend struct ::protobuf_apa_5fmsgs_2fobject_2eproto::TableStruct;
};
// ===================================================================

// ===================================================================

#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif // __GNUC__
// Object

// .raincom.apa.msgs.Header header = 1;
inline bool Object::has_header() const
{
    return this != internal_default_instance() && header_ != NULL;
}
inline const ::raincom::apa::msgs::Header &Object::_internal_header() const
{
    return *header_;
}
inline const ::raincom::apa::msgs::Header &Object::header() const
{
    const ::raincom::apa::msgs::Header *p = header_;
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Object.header)
    return p != NULL ? *p
                     : *reinterpret_cast<const ::raincom::apa::msgs::Header *>(
                           &::raincom::apa::msgs::_Header_default_instance_);
}
inline ::raincom::apa::msgs::Header *Object::release_header()
{
    // @@protoc_insertion_point(field_release:raincom.apa.msgs.Object.header)

    ::raincom::apa::msgs::Header *temp = header_;
    header_                            = NULL;
    return temp;
}
inline ::raincom::apa::msgs::Header *Object::mutable_header()
{

    if (header_ == NULL)
    {
        auto *p = CreateMaybeMessage<::raincom::apa::msgs::Header>(GetArenaNoVirtual());
        header_ = p;
    }
    // @@protoc_insertion_point(field_mutable:raincom.apa.msgs.Object.header)
    return header_;
}
inline void Object::set_allocated_header(::raincom::apa::msgs::Header *header)
{
    ::google::protobuf::Arena *message_arena = GetArenaNoVirtual();
    if (message_arena == NULL)
    {
        delete reinterpret_cast<::google::protobuf::MessageLite *>(header_);
    }
    if (header)
    {
        ::google::protobuf::Arena *submessage_arena = NULL;
        if (message_arena != submessage_arena)
        {
            header = ::google::protobuf::internal::GetOwnedMessage(message_arena, header,
                                                                   submessage_arena);
        }
    }
    else
    {
    }
    header_ = header;
    // @@protoc_insertion_point(field_set_allocated:raincom.apa.msgs.Object.header)
}

// float conf = 2;
inline void Object::clear_conf() { conf_ = 0; }
inline float Object::conf() const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Object.conf)
    return conf_;
}
inline void Object::set_conf(float value)
{

    conf_ = value;
    // @@protoc_insertion_point(field_set:raincom.apa.msgs.Object.conf)
}

// int32 age = 3;
inline void Object::clear_age() { age_ = 0; }
inline ::google::protobuf::int32 Object::age() const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Object.age)
    return age_;
}
inline void Object::set_age(::google::protobuf::int32 value)
{

    age_ = value;
    // @@protoc_insertion_point(field_set:raincom.apa.msgs.Object.age)
}

// .raincom.apa.msgs.Object.Sensor sensor = 4;
inline void Object::clear_sensor() { sensor_ = 0; }
inline ::raincom::apa::msgs::Object_Sensor Object::sensor() const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Object.sensor)
    return static_cast<::raincom::apa::msgs::Object_Sensor>(sensor_);
}
inline void Object::set_sensor(::raincom::apa::msgs::Object_Sensor value)
{

    sensor_ = value;
    // @@protoc_insertion_point(field_set:raincom.apa.msgs.Object.sensor)
}

// .raincom.apa.msgs.TrackState track_state = 5;
inline void Object::clear_track_state() { track_state_ = 0; }
inline ::raincom::apa::msgs::TrackState Object::track_state() const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Object.track_state)
    return static_cast<::raincom::apa::msgs::TrackState>(track_state_);
}
inline void Object::set_track_state(::raincom::apa::msgs::TrackState value)
{

    track_state_ = value;
    // @@protoc_insertion_point(field_set:raincom.apa.msgs.Object.track_state)
}

// repeated int32 ref_slots = 6;
inline int Object::ref_slots_size() const { return ref_slots_.size(); }
inline void Object::clear_ref_slots() { ref_slots_.Clear(); }
inline ::google::protobuf::int32 Object::ref_slots(int index) const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Object.ref_slots)
    return ref_slots_.Get(index);
}
inline void Object::set_ref_slots(int index, ::google::protobuf::int32 value)
{
    ref_slots_.Set(index, value);
    // @@protoc_insertion_point(field_set:raincom.apa.msgs.Object.ref_slots)
}
inline void Object::add_ref_slots(::google::protobuf::int32 value)
{
    ref_slots_.Add(value);
    // @@protoc_insertion_point(field_add:raincom.apa.msgs.Object.ref_slots)
}
inline const ::google::protobuf::RepeatedField<::google::protobuf::int32>
    &Object::ref_slots() const
{
    // @@protoc_insertion_point(field_list:raincom.apa.msgs.Object.ref_slots)
    return ref_slots_;
}
inline ::google::protobuf::RepeatedField<::google::protobuf::int32>
    *Object::mutable_ref_slots()
{
    // @@protoc_insertion_point(field_mutable_list:raincom.apa.msgs.Object.ref_slots)
    return &ref_slots_;
}

// .raincom.apa.msgs.Vec3 shape = 7;
inline bool Object::has_shape() const
{
    return this != internal_default_instance() && shape_ != NULL;
}
inline const ::raincom::apa::msgs::Vec3 &Object::_internal_shape() const
{
    return *shape_;
}
inline const ::raincom::apa::msgs::Vec3 &Object::shape() const
{
    const ::raincom::apa::msgs::Vec3 *p = shape_;
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Object.shape)
    return p != NULL ? *p
                     : *reinterpret_cast<const ::raincom::apa::msgs::Vec3 *>(
                           &::raincom::apa::msgs::_Vec3_default_instance_);
}
inline ::raincom::apa::msgs::Vec3 *Object::release_shape()
{
    // @@protoc_insertion_point(field_release:raincom.apa.msgs.Object.shape)

    ::raincom::apa::msgs::Vec3 *temp = shape_;
    shape_                           = NULL;
    return temp;
}
inline ::raincom::apa::msgs::Vec3 *Object::mutable_shape()
{

    if (shape_ == NULL)
    {
        auto *p = CreateMaybeMessage<::raincom::apa::msgs::Vec3>(GetArenaNoVirtual());
        shape_  = p;
    }
    // @@protoc_insertion_point(field_mutable:raincom.apa.msgs.Object.shape)
    return shape_;
}
inline void Object::set_allocated_shape(::raincom::apa::msgs::Vec3 *shape)
{
    ::google::protobuf::Arena *message_arena = GetArenaNoVirtual();
    if (message_arena == NULL)
    {
        delete reinterpret_cast<::google::protobuf::MessageLite *>(shape_);
    }
    if (shape)
    {
        ::google::protobuf::Arena *submessage_arena = NULL;
        if (message_arena != submessage_arena)
        {
            shape = ::google::protobuf::internal::GetOwnedMessage(message_arena, shape,
                                                                  submessage_arena);
        }
    }
    else
    {
    }
    shape_ = shape;
    // @@protoc_insertion_point(field_set_allocated:raincom.apa.msgs.Object.shape)
}

// repeated bool shape_valid = 8;
inline int Object::shape_valid_size() const { return shape_valid_.size(); }
inline void Object::clear_shape_valid() { shape_valid_.Clear(); }
inline bool Object::shape_valid(int index) const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Object.shape_valid)
    return shape_valid_.Get(index);
}
inline void Object::set_shape_valid(int index, bool value)
{
    shape_valid_.Set(index, value);
    // @@protoc_insertion_point(field_set:raincom.apa.msgs.Object.shape_valid)
}
inline void Object::add_shape_valid(bool value)
{
    shape_valid_.Add(value);
    // @@protoc_insertion_point(field_add:raincom.apa.msgs.Object.shape_valid)
}
inline const ::google::protobuf::RepeatedField<bool> &Object::shape_valid() const
{
    // @@protoc_insertion_point(field_list:raincom.apa.msgs.Object.shape_valid)
    return shape_valid_;
}
inline ::google::protobuf::RepeatedField<bool> *Object::mutable_shape_valid()
{
    // @@protoc_insertion_point(field_mutable_list:raincom.apa.msgs.Object.shape_valid)
    return &shape_valid_;
}

// .raincom.apa.msgs.Vec3 shape_var = 9;
inline bool Object::has_shape_var() const
{
    return this != internal_default_instance() && shape_var_ != NULL;
}
inline const ::raincom::apa::msgs::Vec3 &Object::_internal_shape_var() const
{
    return *shape_var_;
}
inline const ::raincom::apa::msgs::Vec3 &Object::shape_var() const
{
    const ::raincom::apa::msgs::Vec3 *p = shape_var_;
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Object.shape_var)
    return p != NULL ? *p
                     : *reinterpret_cast<const ::raincom::apa::msgs::Vec3 *>(
                           &::raincom::apa::msgs::_Vec3_default_instance_);
}
inline ::raincom::apa::msgs::Vec3 *Object::release_shape_var()
{
    // @@protoc_insertion_point(field_release:raincom.apa.msgs.Object.shape_var)

    ::raincom::apa::msgs::Vec3 *temp = shape_var_;
    shape_var_                       = NULL;
    return temp;
}
inline ::raincom::apa::msgs::Vec3 *Object::mutable_shape_var()
{

    if (shape_var_ == NULL)
    {
        auto *p    = CreateMaybeMessage<::raincom::apa::msgs::Vec3>(GetArenaNoVirtual());
        shape_var_ = p;
    }
    // @@protoc_insertion_point(field_mutable:raincom.apa.msgs.Object.shape_var)
    return shape_var_;
}
inline void Object::set_allocated_shape_var(::raincom::apa::msgs::Vec3 *shape_var)
{
    ::google::protobuf::Arena *message_arena = GetArenaNoVirtual();
    if (message_arena == NULL)
    {
        delete reinterpret_cast<::google::protobuf::MessageLite *>(shape_var_);
    }
    if (shape_var)
    {
        ::google::protobuf::Arena *submessage_arena = NULL;
        if (message_arena != submessage_arena)
        {
            shape_var = ::google::protobuf::internal::GetOwnedMessage(
                message_arena, shape_var, submessage_arena);
        }
    }
    else
    {
    }
    shape_var_ = shape_var;
    // @@protoc_insertion_point(field_set_allocated:raincom.apa.msgs.Object.shape_var)
}

// float ori = 10;
inline void Object::clear_ori() { ori_ = 0; }
inline float Object::ori() const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Object.ori)
    return ori_;
}
inline void Object::set_ori(float value)
{

    ori_ = value;
    // @@protoc_insertion_point(field_set:raincom.apa.msgs.Object.ori)
}

// float ori_var = 11;
inline void Object::clear_ori_var() { ori_var_ = 0; }
inline float Object::ori_var() const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Object.ori_var)
    return ori_var_;
}
inline void Object::set_ori_var(float value)
{

    ori_var_ = value;
    // @@protoc_insertion_point(field_set:raincom.apa.msgs.Object.ori_var)
}

// .raincom.apa.msgs.Object.Clf clf = 12;
inline void Object::clear_clf() { clf_ = 0; }
inline ::raincom::apa::msgs::Object_Clf Object::clf() const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Object.clf)
    return static_cast<::raincom::apa::msgs::Object_Clf>(clf_);
}
inline void Object::set_clf(::raincom::apa::msgs::Object_Clf value)
{

    clf_ = value;
    // @@protoc_insertion_point(field_set:raincom.apa.msgs.Object.clf)
}

// float clf_conf = 13;
inline void Object::clear_clf_conf() { clf_conf_ = 0; }
inline float Object::clf_conf() const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Object.clf_conf)
    return clf_conf_;
}
inline void Object::set_clf_conf(float value)
{

    clf_conf_ = value;
    // @@protoc_insertion_point(field_set:raincom.apa.msgs.Object.clf_conf)
}

// .raincom.apa.msgs.Vec2 nearest = 14;
inline bool Object::has_nearest() const
{
    return this != internal_default_instance() && nearest_ != NULL;
}
inline const ::raincom::apa::msgs::Vec2 &Object::_internal_nearest() const
{
    return *nearest_;
}
inline const ::raincom::apa::msgs::Vec2 &Object::nearest() const
{
    const ::raincom::apa::msgs::Vec2 *p = nearest_;
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Object.nearest)
    return p != NULL ? *p
                     : *reinterpret_cast<const ::raincom::apa::msgs::Vec2 *>(
                           &::raincom::apa::msgs::_Vec2_default_instance_);
}
inline ::raincom::apa::msgs::Vec2 *Object::release_nearest()
{
    // @@protoc_insertion_point(field_release:raincom.apa.msgs.Object.nearest)

    ::raincom::apa::msgs::Vec2 *temp = nearest_;
    nearest_                         = NULL;
    return temp;
}
inline ::raincom::apa::msgs::Vec2 *Object::mutable_nearest()
{

    if (nearest_ == NULL)
    {
        auto *p  = CreateMaybeMessage<::raincom::apa::msgs::Vec2>(GetArenaNoVirtual());
        nearest_ = p;
    }
    // @@protoc_insertion_point(field_mutable:raincom.apa.msgs.Object.nearest)
    return nearest_;
}
inline void Object::set_allocated_nearest(::raincom::apa::msgs::Vec2 *nearest)
{
    ::google::protobuf::Arena *message_arena = GetArenaNoVirtual();
    if (message_arena == NULL)
    {
        delete reinterpret_cast<::google::protobuf::MessageLite *>(nearest_);
    }
    if (nearest)
    {
        ::google::protobuf::Arena *submessage_arena = NULL;
        if (message_arena != submessage_arena)
        {
            nearest = ::google::protobuf::internal::GetOwnedMessage(
                message_arena, nearest, submessage_arena);
        }
    }
    else
    {
    }
    nearest_ = nearest;
    // @@protoc_insertion_point(field_set_allocated:raincom.apa.msgs.Object.nearest)
}

// bool nearest_valid = 15;
inline void Object::clear_nearest_valid() { nearest_valid_ = false; }
inline bool Object::nearest_valid() const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Object.nearest_valid)
    return nearest_valid_;
}
inline void Object::set_nearest_valid(bool value)
{

    nearest_valid_ = value;
    // @@protoc_insertion_point(field_set:raincom.apa.msgs.Object.nearest_valid)
}

// .raincom.apa.msgs.Vec2 nearest_var = 16;
inline bool Object::has_nearest_var() const
{
    return this != internal_default_instance() && nearest_var_ != NULL;
}
inline const ::raincom::apa::msgs::Vec2 &Object::_internal_nearest_var() const
{
    return *nearest_var_;
}
inline const ::raincom::apa::msgs::Vec2 &Object::nearest_var() const
{
    const ::raincom::apa::msgs::Vec2 *p = nearest_var_;
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Object.nearest_var)
    return p != NULL ? *p
                     : *reinterpret_cast<const ::raincom::apa::msgs::Vec2 *>(
                           &::raincom::apa::msgs::_Vec2_default_instance_);
}
inline ::raincom::apa::msgs::Vec2 *Object::release_nearest_var()
{
    // @@protoc_insertion_point(field_release:raincom.apa.msgs.Object.nearest_var)

    ::raincom::apa::msgs::Vec2 *temp = nearest_var_;
    nearest_var_                     = NULL;
    return temp;
}
inline ::raincom::apa::msgs::Vec2 *Object::mutable_nearest_var()
{

    if (nearest_var_ == NULL)
    {
        auto *p = CreateMaybeMessage<::raincom::apa::msgs::Vec2>(GetArenaNoVirtual());
        nearest_var_ = p;
    }
    // @@protoc_insertion_point(field_mutable:raincom.apa.msgs.Object.nearest_var)
    return nearest_var_;
}
inline void Object::set_allocated_nearest_var(::raincom::apa::msgs::Vec2 *nearest_var)
{
    ::google::protobuf::Arena *message_arena = GetArenaNoVirtual();
    if (message_arena == NULL)
    {
        delete reinterpret_cast<::google::protobuf::MessageLite *>(nearest_var_);
    }
    if (nearest_var)
    {
        ::google::protobuf::Arena *submessage_arena = NULL;
        if (message_arena != submessage_arena)
        {
            nearest_var = ::google::protobuf::internal::GetOwnedMessage(
                message_arena, nearest_var, submessage_arena);
        }
    }
    else
    {
    }
    nearest_var_ = nearest_var;
    // @@protoc_insertion_point(field_set_allocated:raincom.apa.msgs.Object.nearest_var)
}

// .raincom.apa.msgs.Vec2 center = 17;
inline bool Object::has_center() const
{
    return this != internal_default_instance() && center_ != NULL;
}
inline const ::raincom::apa::msgs::Vec2 &Object::_internal_center() const
{
    return *center_;
}
inline const ::raincom::apa::msgs::Vec2 &Object::center() const
{
    const ::raincom::apa::msgs::Vec2 *p = center_;
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Object.center)
    return p != NULL ? *p
                     : *reinterpret_cast<const ::raincom::apa::msgs::Vec2 *>(
                           &::raincom::apa::msgs::_Vec2_default_instance_);
}
inline ::raincom::apa::msgs::Vec2 *Object::release_center()
{
    // @@protoc_insertion_point(field_release:raincom.apa.msgs.Object.center)

    ::raincom::apa::msgs::Vec2 *temp = center_;
    center_                          = NULL;
    return temp;
}
inline ::raincom::apa::msgs::Vec2 *Object::mutable_center()
{

    if (center_ == NULL)
    {
        auto *p = CreateMaybeMessage<::raincom::apa::msgs::Vec2>(GetArenaNoVirtual());
        center_ = p;
    }
    // @@protoc_insertion_point(field_mutable:raincom.apa.msgs.Object.center)
    return center_;
}
inline void Object::set_allocated_center(::raincom::apa::msgs::Vec2 *center)
{
    ::google::protobuf::Arena *message_arena = GetArenaNoVirtual();
    if (message_arena == NULL)
    {
        delete reinterpret_cast<::google::protobuf::MessageLite *>(center_);
    }
    if (center)
    {
        ::google::protobuf::Arena *submessage_arena = NULL;
        if (message_arena != submessage_arena)
        {
            center = ::google::protobuf::internal::GetOwnedMessage(message_arena, center,
                                                                   submessage_arena);
        }
    }
    else
    {
    }
    center_ = center;
    // @@protoc_insertion_point(field_set_allocated:raincom.apa.msgs.Object.center)
}

// bool center_valid = 18;
inline void Object::clear_center_valid() { center_valid_ = false; }
inline bool Object::center_valid() const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Object.center_valid)
    return center_valid_;
}
inline void Object::set_center_valid(bool value)
{

    center_valid_ = value;
    // @@protoc_insertion_point(field_set:raincom.apa.msgs.Object.center_valid)
}

// .raincom.apa.msgs.Vec2 center_var = 19;
inline bool Object::has_center_var() const
{
    return this != internal_default_instance() && center_var_ != NULL;
}
inline const ::raincom::apa::msgs::Vec2 &Object::_internal_center_var() const
{
    return *center_var_;
}
inline const ::raincom::apa::msgs::Vec2 &Object::center_var() const
{
    const ::raincom::apa::msgs::Vec2 *p = center_var_;
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Object.center_var)
    return p != NULL ? *p
                     : *reinterpret_cast<const ::raincom::apa::msgs::Vec2 *>(
                           &::raincom::apa::msgs::_Vec2_default_instance_);
}
inline ::raincom::apa::msgs::Vec2 *Object::release_center_var()
{
    // @@protoc_insertion_point(field_release:raincom.apa.msgs.Object.center_var)

    ::raincom::apa::msgs::Vec2 *temp = center_var_;
    center_var_                      = NULL;
    return temp;
}
inline ::raincom::apa::msgs::Vec2 *Object::mutable_center_var()
{

    if (center_var_ == NULL)
    {
        auto *p     = CreateMaybeMessage<::raincom::apa::msgs::Vec2>(GetArenaNoVirtual());
        center_var_ = p;
    }
    // @@protoc_insertion_point(field_mutable:raincom.apa.msgs.Object.center_var)
    return center_var_;
}
inline void Object::set_allocated_center_var(::raincom::apa::msgs::Vec2 *center_var)
{
    ::google::protobuf::Arena *message_arena = GetArenaNoVirtual();
    if (message_arena == NULL)
    {
        delete reinterpret_cast<::google::protobuf::MessageLite *>(center_var_);
    }
    if (center_var)
    {
        ::google::protobuf::Arena *submessage_arena = NULL;
        if (message_arena != submessage_arena)
        {
            center_var = ::google::protobuf::internal::GetOwnedMessage(
                message_arena, center_var, submessage_arena);
        }
    }
    else
    {
    }
    center_var_ = center_var;
    // @@protoc_insertion_point(field_set_allocated:raincom.apa.msgs.Object.center_var)
}

// repeated .raincom.apa.msgs.Vec2 corners = 20;
inline int Object::corners_size() const { return corners_.size(); }
inline ::raincom::apa::msgs::Vec2 *Object::mutable_corners(int index)
{
    // @@protoc_insertion_point(field_mutable:raincom.apa.msgs.Object.corners)
    return corners_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Vec2>
    *Object::mutable_corners()
{
    // @@protoc_insertion_point(field_mutable_list:raincom.apa.msgs.Object.corners)
    return &corners_;
}
inline const ::raincom::apa::msgs::Vec2 &Object::corners(int index) const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Object.corners)
    return corners_.Get(index);
}
inline ::raincom::apa::msgs::Vec2 *Object::add_corners()
{
    // @@protoc_insertion_point(field_add:raincom.apa.msgs.Object.corners)
    return corners_.Add();
}
inline const ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Vec2>
    &Object::corners() const
{
    // @@protoc_insertion_point(field_list:raincom.apa.msgs.Object.corners)
    return corners_;
}

// repeated bool corners_valid = 21;
inline int Object::corners_valid_size() const { return corners_valid_.size(); }
inline void Object::clear_corners_valid() { corners_valid_.Clear(); }
inline bool Object::corners_valid(int index) const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Object.corners_valid)
    return corners_valid_.Get(index);
}
inline void Object::set_corners_valid(int index, bool value)
{
    corners_valid_.Set(index, value);
    // @@protoc_insertion_point(field_set:raincom.apa.msgs.Object.corners_valid)
}
inline void Object::add_corners_valid(bool value)
{
    corners_valid_.Add(value);
    // @@protoc_insertion_point(field_add:raincom.apa.msgs.Object.corners_valid)
}
inline const ::google::protobuf::RepeatedField<bool> &Object::corners_valid() const
{
    // @@protoc_insertion_point(field_list:raincom.apa.msgs.Object.corners_valid)
    return corners_valid_;
}
inline ::google::protobuf::RepeatedField<bool> *Object::mutable_corners_valid()
{
    // @@protoc_insertion_point(field_mutable_list:raincom.apa.msgs.Object.corners_valid)
    return &corners_valid_;
}

// repeated .raincom.apa.msgs.Vec2 corners_var = 22;
inline int Object::corners_var_size() const { return corners_var_.size(); }
inline ::raincom::apa::msgs::Vec2 *Object::mutable_corners_var(int index)
{
    // @@protoc_insertion_point(field_mutable:raincom.apa.msgs.Object.corners_var)
    return corners_var_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Vec2>
    *Object::mutable_corners_var()
{
    // @@protoc_insertion_point(field_mutable_list:raincom.apa.msgs.Object.corners_var)
    return &corners_var_;
}
inline const ::raincom::apa::msgs::Vec2 &Object::corners_var(int index) const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Object.corners_var)
    return corners_var_.Get(index);
}
inline ::raincom::apa::msgs::Vec2 *Object::add_corners_var()
{
    // @@protoc_insertion_point(field_add:raincom.apa.msgs.Object.corners_var)
    return corners_var_.Add();
}
inline const ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Vec2>
    &Object::corners_var() const
{
    // @@protoc_insertion_point(field_list:raincom.apa.msgs.Object.corners_var)
    return corners_var_;
}

// repeated .raincom.apa.msgs.Vec2 reliable_corners = 23;
inline int Object::reliable_corners_size() const { return reliable_corners_.size(); }
inline ::raincom::apa::msgs::Vec2 *Object::mutable_reliable_corners(int index)
{
    // @@protoc_insertion_point(field_mutable:raincom.apa.msgs.Object.reliable_corners)
    return reliable_corners_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Vec2>
    *Object::mutable_reliable_corners()
{
    // @@protoc_insertion_point(field_mutable_list:raincom.apa.msgs.Object.reliable_corners)
    return &reliable_corners_;
}
inline const ::raincom::apa::msgs::Vec2 &Object::reliable_corners(int index) const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Object.reliable_corners)
    return reliable_corners_.Get(index);
}
inline ::raincom::apa::msgs::Vec2 *Object::add_reliable_corners()
{
    // @@protoc_insertion_point(field_add:raincom.apa.msgs.Object.reliable_corners)
    return reliable_corners_.Add();
}
inline const ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Vec2>
    &Object::reliable_corners() const
{
    // @@protoc_insertion_point(field_list:raincom.apa.msgs.Object.reliable_corners)
    return reliable_corners_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif // __GNUC__

// @@protoc_insertion_point(namespace_scope)

} // namespace msgs
} // namespace apa
} // namespace raincom

namespace google
{
namespace protobuf
{

template <>
struct is_proto_enum<::raincom::apa::msgs::Object_Sensor> : ::std::true_type
{
};
template <>
inline const EnumDescriptor *GetEnumDescriptor<::raincom::apa::msgs::Object_Sensor>()
{
    return ::raincom::apa::msgs::Object_Sensor_descriptor();
}
template <>
struct is_proto_enum<::raincom::apa::msgs::Object_Clf> : ::std::true_type
{
};
template <>
inline const EnumDescriptor *GetEnumDescriptor<::raincom::apa::msgs::Object_Clf>()
{
    return ::raincom::apa::msgs::Object_Clf_descriptor();
}

} // namespace protobuf
} // namespace google

// @@protoc_insertion_point(global_scope)

#endif // PROTOBUF_INCLUDED_apa_5fmsgs_2fobject_2eproto
