// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apa_msgs/slot.proto

#ifndef PROTOBUF_INCLUDED_apa_5fmsgs_2fslot_2eproto
#define PROTOBUF_INCLUDED_apa_5fmsgs_2fslot_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h> // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "apa_msgs/common.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_apa_5fmsgs_2fslot_2eproto

namespace protobuf_apa_5fmsgs_2fslot_2eproto
{
// Internal implementation detail -- do not use these members.
struct TableStruct
{
    static const ::google::protobuf::internal::ParseTableField entries[];
    static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
    static const ::google::protobuf::internal::ParseTable schema[1];
    static const ::google::protobuf::internal::FieldMetadata field_metadata[];
    static const ::google::protobuf::internal::SerializationTable serialization_table[];
    static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
} // namespace protobuf_apa_5fmsgs_2fslot_2eproto
namespace raincom
{
namespace apa
{
namespace msgs
{
class Slot;
class SlotDefaultTypeInternal;
extern SlotDefaultTypeInternal _Slot_default_instance_;
} // namespace msgs
} // namespace apa
} // namespace raincom
namespace google
{
namespace protobuf
{
template <>
::raincom::apa::msgs::Slot *Arena::CreateMaybeMessage<::raincom::apa::msgs::Slot>(
    Arena *);
} // namespace protobuf
} // namespace google
namespace raincom
{
namespace apa
{
namespace msgs
{

enum Slot_Type
{
    Slot_Type_UNKNOW_TYPE                            = 0,
    Slot_Type_PARALLEL                               = 1,
    Slot_Type_VERTICAL                               = 2,
    Slot_Type_TILT                                   = 3,
    Slot_Type_Slot_Type_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
    Slot_Type_Slot_Type_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Slot_Type_IsValid(int value);
const Slot_Type Slot_Type_Type_MIN = Slot_Type_UNKNOW_TYPE;
const Slot_Type Slot_Type_Type_MAX = Slot_Type_TILT;
const int Slot_Type_Type_ARRAYSIZE = Slot_Type_Type_MAX + 1;

const ::google::protobuf::EnumDescriptor *Slot_Type_descriptor();
inline const ::std::string &Slot_Type_Name(Slot_Type value)
{
    return ::google::protobuf::internal::NameOfEnum(Slot_Type_descriptor(), value);
}
inline bool Slot_Type_Parse(const ::std::string &name, Slot_Type *value)
{
    return ::google::protobuf::internal::ParseNamedEnum<Slot_Type>(Slot_Type_descriptor(),
                                                                   name, value);
}
enum Slot_LockerState
{
    Slot_LockerState_NOT_FOUND = 0,
    Slot_LockerState_OPENED    = 1,
    Slot_LockerState_CLOSED    = 2,
    Slot_LockerState_Slot_LockerState_INT_MIN_SENTINEL_DO_NOT_USE_ =
        ::google::protobuf::kint32min,
    Slot_LockerState_Slot_LockerState_INT_MAX_SENTINEL_DO_NOT_USE_ =
        ::google::protobuf::kint32max
};
bool Slot_LockerState_IsValid(int value);
const Slot_LockerState Slot_LockerState_LockerState_MIN = Slot_LockerState_NOT_FOUND;
const Slot_LockerState Slot_LockerState_LockerState_MAX = Slot_LockerState_CLOSED;
const int Slot_LockerState_LockerState_ARRAYSIZE = Slot_LockerState_LockerState_MAX + 1;

const ::google::protobuf::EnumDescriptor *Slot_LockerState_descriptor();
inline const ::std::string &Slot_LockerState_Name(Slot_LockerState value)
{
    return ::google::protobuf::internal::NameOfEnum(Slot_LockerState_descriptor(), value);
}
inline bool Slot_LockerState_Parse(const ::std::string &name, Slot_LockerState *value)
{
    return ::google::protobuf::internal::ParseNamedEnum<Slot_LockerState>(
        Slot_LockerState_descriptor(), name, value);
}
enum Slot_OccupyState
{
    Slot_OccupyState_NO  = 0,
    Slot_OccupyState_YES = 1,
    Slot_OccupyState_Slot_OccupyState_INT_MIN_SENTINEL_DO_NOT_USE_ =
        ::google::protobuf::kint32min,
    Slot_OccupyState_Slot_OccupyState_INT_MAX_SENTINEL_DO_NOT_USE_ =
        ::google::protobuf::kint32max
};
bool Slot_OccupyState_IsValid(int value);
const Slot_OccupyState Slot_OccupyState_OccupyState_MIN = Slot_OccupyState_NO;
const Slot_OccupyState Slot_OccupyState_OccupyState_MAX = Slot_OccupyState_YES;
const int Slot_OccupyState_OccupyState_ARRAYSIZE = Slot_OccupyState_OccupyState_MAX + 1;

const ::google::protobuf::EnumDescriptor *Slot_OccupyState_descriptor();
inline const ::std::string &Slot_OccupyState_Name(Slot_OccupyState value)
{
    return ::google::protobuf::internal::NameOfEnum(Slot_OccupyState_descriptor(), value);
}
inline bool Slot_OccupyState_Parse(const ::std::string &name, Slot_OccupyState *value)
{
    return ::google::protobuf::internal::ParseNamedEnum<Slot_OccupyState>(
        Slot_OccupyState_descriptor(), name, value);
}
enum Slot_CornerOrder
{
    Slot_CornerOrder_UNKNOWN_ORDER = 0,
    Slot_CornerOrder_CLK_WISE      = 1,
    Slot_CornerOrder_COUNTER_CLK   = 2,
    Slot_CornerOrder_Slot_CornerOrder_INT_MIN_SENTINEL_DO_NOT_USE_ =
        ::google::protobuf::kint32min,
    Slot_CornerOrder_Slot_CornerOrder_INT_MAX_SENTINEL_DO_NOT_USE_ =
        ::google::protobuf::kint32max
};
bool Slot_CornerOrder_IsValid(int value);
const Slot_CornerOrder Slot_CornerOrder_CornerOrder_MIN = Slot_CornerOrder_UNKNOWN_ORDER;
const Slot_CornerOrder Slot_CornerOrder_CornerOrder_MAX = Slot_CornerOrder_COUNTER_CLK;
const int Slot_CornerOrder_CornerOrder_ARRAYSIZE = Slot_CornerOrder_CornerOrder_MAX + 1;

const ::google::protobuf::EnumDescriptor *Slot_CornerOrder_descriptor();
inline const ::std::string &Slot_CornerOrder_Name(Slot_CornerOrder value)
{
    return ::google::protobuf::internal::NameOfEnum(Slot_CornerOrder_descriptor(), value);
}
inline bool Slot_CornerOrder_Parse(const ::std::string &name, Slot_CornerOrder *value)
{
    return ::google::protobuf::internal::ParseNamedEnum<Slot_CornerOrder>(
        Slot_CornerOrder_descriptor(), name, value);
}
// ===================================================================

class Slot : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:raincom.apa.msgs.Slot)
                                                 */
{
  public:
    Slot();
    virtual ~Slot();

    Slot(const Slot &from);

    inline Slot &operator=(const Slot &from)
    {
        CopyFrom(from);
        return *this;
    }
#if LANG_CXX11
    Slot(Slot &&from) noexcept : Slot() { *this = ::std::move(from); }

    inline Slot &operator=(Slot &&from) noexcept
    {
        if (GetArenaNoVirtual() == from.GetArenaNoVirtual())
        {
            if (this != &from)
                InternalSwap(&from);
        }
        else
        {
            CopyFrom(from);
        }
        return *this;
    }
#endif
    static const ::google::protobuf::Descriptor *descriptor();
    static const Slot &default_instance();

    static void InitAsDefaultInstance(); // FOR INTERNAL USE ONLY
    static inline const Slot *internal_default_instance()
    {
        return reinterpret_cast<const Slot *>(&_Slot_default_instance_);
    }
    static constexpr int kIndexInFileMessages = 0;

    void Swap(Slot *other);
    friend void swap(Slot &a, Slot &b) { a.Swap(&b); }

    // implements Message ----------------------------------------------

    inline Slot *New() const final { return CreateMaybeMessage<Slot>(NULL); }

    Slot *New(::google::protobuf::Arena *arena) const final
    {
        return CreateMaybeMessage<Slot>(arena);
    }
    void CopyFrom(const ::google::protobuf::Message &from) final;
    void MergeFrom(const ::google::protobuf::Message &from) final;
    void CopyFrom(const Slot &from);
    void MergeFrom(const Slot &from);
    void Clear() final;
    bool IsInitialized() const final;

    size_t ByteSizeLong() const final;
    bool MergePartialFromCodedStream(
        ::google::protobuf::io::CodedInputStream *input) final;
    void SerializeWithCachedSizes(
        ::google::protobuf::io::CodedOutputStream *output) const final;
    ::google::protobuf::uint8 *InternalSerializeWithCachedSizesToArray(
        bool deterministic, ::google::protobuf::uint8 *target) const final;
    int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
    void SharedCtor();
    void SharedDtor();
    void SetCachedSize(int size) const final;
    void InternalSwap(Slot *other);

  private:
    inline ::google::protobuf::Arena *GetArenaNoVirtual() const { return NULL; }
    inline void *MaybeArenaPtr() const { return NULL; }

  public:
    ::google::protobuf::Metadata GetMetadata() const final;

    // nested types ----------------------------------------------------

    typedef Slot_Type Type;
    static const Type UNKNOW_TYPE = Slot_Type_UNKNOW_TYPE;
    static const Type PARALLEL    = Slot_Type_PARALLEL;
    static const Type VERTICAL    = Slot_Type_VERTICAL;
    static const Type TILT        = Slot_Type_TILT;
    static inline bool Type_IsValid(int value) { return Slot_Type_IsValid(value); }
    static const Type Type_MIN      = Slot_Type_Type_MIN;
    static const Type Type_MAX      = Slot_Type_Type_MAX;
    static const int Type_ARRAYSIZE = Slot_Type_Type_ARRAYSIZE;
    static inline const ::google::protobuf::EnumDescriptor *Type_descriptor()
    {
        return Slot_Type_descriptor();
    }
    static inline const ::std::string &Type_Name(Type value)
    {
        return Slot_Type_Name(value);
    }
    static inline bool Type_Parse(const ::std::string &name, Type *value)
    {
        return Slot_Type_Parse(name, value);
    }

    typedef Slot_LockerState LockerState;
    static const LockerState NOT_FOUND = Slot_LockerState_NOT_FOUND;
    static const LockerState OPENED    = Slot_LockerState_OPENED;
    static const LockerState CLOSED    = Slot_LockerState_CLOSED;
    static inline bool LockerState_IsValid(int value)
    {
        return Slot_LockerState_IsValid(value);
    }
    static const LockerState LockerState_MIN = Slot_LockerState_LockerState_MIN;
    static const LockerState LockerState_MAX = Slot_LockerState_LockerState_MAX;
    static const int LockerState_ARRAYSIZE   = Slot_LockerState_LockerState_ARRAYSIZE;
    static inline const ::google::protobuf::EnumDescriptor *LockerState_descriptor()
    {
        return Slot_LockerState_descriptor();
    }
    static inline const ::std::string &LockerState_Name(LockerState value)
    {
        return Slot_LockerState_Name(value);
    }
    static inline bool LockerState_Parse(const ::std::string &name, LockerState *value)
    {
        return Slot_LockerState_Parse(name, value);
    }

    typedef Slot_OccupyState OccupyState;
    static const OccupyState NO  = Slot_OccupyState_NO;
    static const OccupyState YES = Slot_OccupyState_YES;
    static inline bool OccupyState_IsValid(int value)
    {
        return Slot_OccupyState_IsValid(value);
    }
    static const OccupyState OccupyState_MIN = Slot_OccupyState_OccupyState_MIN;
    static const OccupyState OccupyState_MAX = Slot_OccupyState_OccupyState_MAX;
    static const int OccupyState_ARRAYSIZE   = Slot_OccupyState_OccupyState_ARRAYSIZE;
    static inline const ::google::protobuf::EnumDescriptor *OccupyState_descriptor()
    {
        return Slot_OccupyState_descriptor();
    }
    static inline const ::std::string &OccupyState_Name(OccupyState value)
    {
        return Slot_OccupyState_Name(value);
    }
    static inline bool OccupyState_Parse(const ::std::string &name, OccupyState *value)
    {
        return Slot_OccupyState_Parse(name, value);
    }

    typedef Slot_CornerOrder CornerOrder;
    static const CornerOrder UNKNOWN_ORDER = Slot_CornerOrder_UNKNOWN_ORDER;
    static const CornerOrder CLK_WISE      = Slot_CornerOrder_CLK_WISE;
    static const CornerOrder COUNTER_CLK   = Slot_CornerOrder_COUNTER_CLK;
    static inline bool CornerOrder_IsValid(int value)
    {
        return Slot_CornerOrder_IsValid(value);
    }
    static const CornerOrder CornerOrder_MIN = Slot_CornerOrder_CornerOrder_MIN;
    static const CornerOrder CornerOrder_MAX = Slot_CornerOrder_CornerOrder_MAX;
    static const int CornerOrder_ARRAYSIZE   = Slot_CornerOrder_CornerOrder_ARRAYSIZE;
    static inline const ::google::protobuf::EnumDescriptor *CornerOrder_descriptor()
    {
        return Slot_CornerOrder_descriptor();
    }
    static inline const ::std::string &CornerOrder_Name(CornerOrder value)
    {
        return Slot_CornerOrder_Name(value);
    }
    static inline bool CornerOrder_Parse(const ::std::string &name, CornerOrder *value)
    {
        return Slot_CornerOrder_Parse(name, value);
    }

    // accessors -------------------------------------------------------

    // repeated .raincom.apa.msgs.Vec2 corners = 15;
    int corners_size() const;
    void clear_corners();
    static const int kCornersFieldNumber = 15;
    ::raincom::apa::msgs::Vec2 *mutable_corners(int index);
    ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Vec2> *mutable_corners();
    const ::raincom::apa::msgs::Vec2 &corners(int index) const;
    ::raincom::apa::msgs::Vec2 *add_corners();
    const ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Vec2> &corners()
        const;

    // repeated .raincom.apa.msgs.Vec2 corners_var = 16;
    int corners_var_size() const;
    void clear_corners_var();
    static const int kCornersVarFieldNumber = 16;
    ::raincom::apa::msgs::Vec2 *mutable_corners_var(int index);
    ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Vec2>
        *mutable_corners_var();
    const ::raincom::apa::msgs::Vec2 &corners_var(int index) const;
    ::raincom::apa::msgs::Vec2 *add_corners_var();
    const ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Vec2> &corners_var()
        const;

    // repeated int32 ref_objs = 23;
    int ref_objs_size() const;
    void clear_ref_objs();
    static const int kRefObjsFieldNumber = 23;
    ::google::protobuf::int32 ref_objs(int index) const;
    void set_ref_objs(int index, ::google::protobuf::int32 value);
    void add_ref_objs(::google::protobuf::int32 value);
    const ::google::protobuf::RepeatedField<::google::protobuf::int32> &ref_objs() const;
    ::google::protobuf::RepeatedField<::google::protobuf::int32> *mutable_ref_objs();

    // repeated .raincom.apa.msgs.Vec2 stop_bar_pos = 24;
    int stop_bar_pos_size() const;
    void clear_stop_bar_pos();
    static const int kStopBarPosFieldNumber = 24;
    ::raincom::apa::msgs::Vec2 *mutable_stop_bar_pos(int index);
    ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Vec2>
        *mutable_stop_bar_pos();
    const ::raincom::apa::msgs::Vec2 &stop_bar_pos(int index) const;
    ::raincom::apa::msgs::Vec2 *add_stop_bar_pos();
    const ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Vec2> &stop_bar_pos()
        const;

    // repeated .raincom.apa.msgs.Vec2 stop_bar_pos_var = 25;
    int stop_bar_pos_var_size() const;
    void clear_stop_bar_pos_var();
    static const int kStopBarPosVarFieldNumber = 25;
    ::raincom::apa::msgs::Vec2 *mutable_stop_bar_pos_var(int index);
    ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Vec2>
        *mutable_stop_bar_pos_var();
    const ::raincom::apa::msgs::Vec2 &stop_bar_pos_var(int index) const;
    ::raincom::apa::msgs::Vec2 *add_stop_bar_pos_var();
    const ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Vec2>
        &stop_bar_pos_var() const;

    // .raincom.apa.msgs.Header header = 1;
    bool has_header() const;
    void clear_header();
    static const int kHeaderFieldNumber = 1;

  private:
    const ::raincom::apa::msgs::Header &_internal_header() const;

  public:
    const ::raincom::apa::msgs::Header &header() const;
    ::raincom::apa::msgs::Header *release_header();
    ::raincom::apa::msgs::Header *mutable_header();
    void set_allocated_header(::raincom::apa::msgs::Header *header);

    // .raincom.apa.msgs.Vec2 center = 7;
    bool has_center() const;
    void clear_center();
    static const int kCenterFieldNumber = 7;

  private:
    const ::raincom::apa::msgs::Vec2 &_internal_center() const;

  public:
    const ::raincom::apa::msgs::Vec2 &center() const;
    ::raincom::apa::msgs::Vec2 *release_center();
    ::raincom::apa::msgs::Vec2 *mutable_center();
    void set_allocated_center(::raincom::apa::msgs::Vec2 *center);

    // .raincom.apa.msgs.Vec2 center_var = 8;
    bool has_center_var() const;
    void clear_center_var();
    static const int kCenterVarFieldNumber = 8;

  private:
    const ::raincom::apa::msgs::Vec2 &_internal_center_var() const;

  public:
    const ::raincom::apa::msgs::Vec2 &center_var() const;
    ::raincom::apa::msgs::Vec2 *release_center_var();
    ::raincom::apa::msgs::Vec2 *mutable_center_var();
    void set_allocated_center_var(::raincom::apa::msgs::Vec2 *center_var);

    // .raincom.apa.msgs.Slot.Type type = 2;
    void clear_type();
    static const int kTypeFieldNumber = 2;
    ::raincom::apa::msgs::Slot_Type type() const;
    void set_type(::raincom::apa::msgs::Slot_Type value);

    // float conf = 3;
    void clear_conf();
    static const int kConfFieldNumber = 3;
    float conf() const;
    void set_conf(float value);

    // int32 age = 4;
    void clear_age();
    static const int kAgeFieldNumber = 4;
    ::google::protobuf::int32 age() const;
    void set_age(::google::protobuf::int32 value);

    // .raincom.apa.msgs.Slot.CornerOrder corner_order = 5;
    void clear_corner_order();
    static const int kCornerOrderFieldNumber = 5;
    ::raincom::apa::msgs::Slot_CornerOrder corner_order() const;
    void set_corner_order(::raincom::apa::msgs::Slot_CornerOrder value);

    // .raincom.apa.msgs.TrackState track_state = 6;
    void clear_track_state();
    static const int kTrackStateFieldNumber = 6;
    ::raincom::apa::msgs::TrackState track_state() const;
    void set_track_state(::raincom::apa::msgs::TrackState value);

    // .raincom.apa.msgs.Slot.LockerState locker_state = 9;
    void clear_locker_state();
    static const int kLockerStateFieldNumber = 9;
    ::raincom::apa::msgs::Slot_LockerState locker_state() const;
    void set_locker_state(::raincom::apa::msgs::Slot_LockerState value);

    // float locker_conf = 10;
    void clear_locker_conf();
    static const int kLockerConfFieldNumber = 10;
    float locker_conf() const;
    void set_locker_conf(float value);

    // float ori = 11;
    void clear_ori();
    static const int kOriFieldNumber = 11;
    float ori() const;
    void set_ori(float value);

    // float ori_var = 12;
    void clear_ori_var();
    static const int kOriVarFieldNumber = 12;
    float ori_var() const;
    void set_ori_var(float value);

    // float tilt_angle = 13;
    void clear_tilt_angle();
    static const int kTiltAngleFieldNumber = 13;
    float tilt_angle() const;
    void set_tilt_angle(float value);

    // float tilt_angle_var = 14;
    void clear_tilt_angle_var();
    static const int kTiltAngleVarFieldNumber = 14;
    float tilt_angle_var() const;
    void set_tilt_angle_var(float value);

    // float depth = 17;
    void clear_depth();
    static const int kDepthFieldNumber = 17;
    float depth() const;
    void set_depth(float value);

    // float depth_var = 18;
    void clear_depth_var();
    static const int kDepthVarFieldNumber = 18;
    float depth_var() const;
    void set_depth_var(float value);

    // float width = 19;
    void clear_width();
    static const int kWidthFieldNumber = 19;
    float width() const;
    void set_width(float value);

    // float width_var = 20;
    void clear_width_var();
    static const int kWidthVarFieldNumber = 20;
    float width_var() const;
    void set_width_var(float value);

    // .raincom.apa.msgs.Slot.OccupyState occupied = 21;
    void clear_occupied();
    static const int kOccupiedFieldNumber = 21;
    ::raincom::apa::msgs::Slot_OccupyState occupied() const;
    void set_occupied(::raincom::apa::msgs::Slot_OccupyState value);

    // float occupied_conf = 22;
    void clear_occupied_conf();
    static const int kOccupiedConfFieldNumber = 22;
    float occupied_conf() const;
    void set_occupied_conf(float value);

    // float stop_bar_conf = 26;
    void clear_stop_bar_conf();
    static const int kStopBarConfFieldNumber = 26;
    float stop_bar_conf() const;
    void set_stop_bar_conf(float value);

    // float stop_bar_btm = 27;
    void clear_stop_bar_btm();
    static const int kStopBarBtmFieldNumber = 27;
    float stop_bar_btm() const;
    void set_stop_bar_btm(float value);

    // float stop_bar_top = 28;
    void clear_stop_bar_top();
    static const int kStopBarTopFieldNumber = 28;
    float stop_bar_top() const;
    void set_stop_bar_top(float value);

    // @@protoc_insertion_point(class_scope:raincom.apa.msgs.Slot)
  private:
    ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
    ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Vec2> corners_;
    ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Vec2> corners_var_;
    ::google::protobuf::RepeatedField<::google::protobuf::int32> ref_objs_;
    mutable int _ref_objs_cached_byte_size_;
    ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Vec2> stop_bar_pos_;
    ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Vec2> stop_bar_pos_var_;
    ::raincom::apa::msgs::Header *header_;
    ::raincom::apa::msgs::Vec2 *center_;
    ::raincom::apa::msgs::Vec2 *center_var_;
    int type_;
    float conf_;
    ::google::protobuf::int32 age_;
    int corner_order_;
    int track_state_;
    int locker_state_;
    float locker_conf_;
    float ori_;
    float ori_var_;
    float tilt_angle_;
    float tilt_angle_var_;
    float depth_;
    float depth_var_;
    float width_;
    float width_var_;
    int occupied_;
    float occupied_conf_;
    float stop_bar_conf_;
    float stop_bar_btm_;
    float stop_bar_top_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    friend struct ::protobuf_apa_5fmsgs_2fslot_2eproto::TableStruct;
};
// ===================================================================

// ===================================================================

#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif // __GNUC__
// Slot

// .raincom.apa.msgs.Header header = 1;
inline bool Slot::has_header() const
{
    return this != internal_default_instance() && header_ != NULL;
}
inline const ::raincom::apa::msgs::Header &Slot::_internal_header() const
{
    return *header_;
}
inline const ::raincom::apa::msgs::Header &Slot::header() const
{
    const ::raincom::apa::msgs::Header *p = header_;
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Slot.header)
    return p != NULL ? *p
                     : *reinterpret_cast<const ::raincom::apa::msgs::Header *>(
                           &::raincom::apa::msgs::_Header_default_instance_);
}
inline ::raincom::apa::msgs::Header *Slot::release_header()
{
    // @@protoc_insertion_point(field_release:raincom.apa.msgs.Slot.header)

    ::raincom::apa::msgs::Header *temp = header_;
    header_                            = NULL;
    return temp;
}
inline ::raincom::apa::msgs::Header *Slot::mutable_header()
{

    if (header_ == NULL)
    {
        auto *p = CreateMaybeMessage<::raincom::apa::msgs::Header>(GetArenaNoVirtual());
        header_ = p;
    }
    // @@protoc_insertion_point(field_mutable:raincom.apa.msgs.Slot.header)
    return header_;
}
inline void Slot::set_allocated_header(::raincom::apa::msgs::Header *header)
{
    ::google::protobuf::Arena *message_arena = GetArenaNoVirtual();
    if (message_arena == NULL)
    {
        delete reinterpret_cast<::google::protobuf::MessageLite *>(header_);
    }
    if (header)
    {
        ::google::protobuf::Arena *submessage_arena = NULL;
        if (message_arena != submessage_arena)
        {
            header = ::google::protobuf::internal::GetOwnedMessage(message_arena, header,
                                                                   submessage_arena);
        }
    }
    else
    {
    }
    header_ = header;
    // @@protoc_insertion_point(field_set_allocated:raincom.apa.msgs.Slot.header)
}

// .raincom.apa.msgs.Slot.Type type = 2;
inline void Slot::clear_type() { type_ = 0; }
inline ::raincom::apa::msgs::Slot_Type Slot::type() const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Slot.type)
    return static_cast<::raincom::apa::msgs::Slot_Type>(type_);
}
inline void Slot::set_type(::raincom::apa::msgs::Slot_Type value)
{

    type_ = value;
    // @@protoc_insertion_point(field_set:raincom.apa.msgs.Slot.type)
}

// float conf = 3;
inline void Slot::clear_conf() { conf_ = 0; }
inline float Slot::conf() const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Slot.conf)
    return conf_;
}
inline void Slot::set_conf(float value)
{

    conf_ = value;
    // @@protoc_insertion_point(field_set:raincom.apa.msgs.Slot.conf)
}

// int32 age = 4;
inline void Slot::clear_age() { age_ = 0; }
inline ::google::protobuf::int32 Slot::age() const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Slot.age)
    return age_;
}
inline void Slot::set_age(::google::protobuf::int32 value)
{

    age_ = value;
    // @@protoc_insertion_point(field_set:raincom.apa.msgs.Slot.age)
}

// .raincom.apa.msgs.Slot.CornerOrder corner_order = 5;
inline void Slot::clear_corner_order() { corner_order_ = 0; }
inline ::raincom::apa::msgs::Slot_CornerOrder Slot::corner_order() const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Slot.corner_order)
    return static_cast<::raincom::apa::msgs::Slot_CornerOrder>(corner_order_);
}
inline void Slot::set_corner_order(::raincom::apa::msgs::Slot_CornerOrder value)
{

    corner_order_ = value;
    // @@protoc_insertion_point(field_set:raincom.apa.msgs.Slot.corner_order)
}

// .raincom.apa.msgs.TrackState track_state = 6;
inline void Slot::clear_track_state() { track_state_ = 0; }
inline ::raincom::apa::msgs::TrackState Slot::track_state() const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Slot.track_state)
    return static_cast<::raincom::apa::msgs::TrackState>(track_state_);
}
inline void Slot::set_track_state(::raincom::apa::msgs::TrackState value)
{

    track_state_ = value;
    // @@protoc_insertion_point(field_set:raincom.apa.msgs.Slot.track_state)
}

// .raincom.apa.msgs.Vec2 center = 7;
inline bool Slot::has_center() const
{
    return this != internal_default_instance() && center_ != NULL;
}
inline const ::raincom::apa::msgs::Vec2 &Slot::_internal_center() const
{
    return *center_;
}
inline const ::raincom::apa::msgs::Vec2 &Slot::center() const
{
    const ::raincom::apa::msgs::Vec2 *p = center_;
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Slot.center)
    return p != NULL ? *p
                     : *reinterpret_cast<const ::raincom::apa::msgs::Vec2 *>(
                           &::raincom::apa::msgs::_Vec2_default_instance_);
}
inline ::raincom::apa::msgs::Vec2 *Slot::release_center()
{
    // @@protoc_insertion_point(field_release:raincom.apa.msgs.Slot.center)

    ::raincom::apa::msgs::Vec2 *temp = center_;
    center_                          = NULL;
    return temp;
}
inline ::raincom::apa::msgs::Vec2 *Slot::mutable_center()
{

    if (center_ == NULL)
    {
        auto *p = CreateMaybeMessage<::raincom::apa::msgs::Vec2>(GetArenaNoVirtual());
        center_ = p;
    }
    // @@protoc_insertion_point(field_mutable:raincom.apa.msgs.Slot.center)
    return center_;
}
inline void Slot::set_allocated_center(::raincom::apa::msgs::Vec2 *center)
{
    ::google::protobuf::Arena *message_arena = GetArenaNoVirtual();
    if (message_arena == NULL)
    {
        delete reinterpret_cast<::google::protobuf::MessageLite *>(center_);
    }
    if (center)
    {
        ::google::protobuf::Arena *submessage_arena = NULL;
        if (message_arena != submessage_arena)
        {
            center = ::google::protobuf::internal::GetOwnedMessage(message_arena, center,
                                                                   submessage_arena);
        }
    }
    else
    {
    }
    center_ = center;
    // @@protoc_insertion_point(field_set_allocated:raincom.apa.msgs.Slot.center)
}

// .raincom.apa.msgs.Vec2 center_var = 8;
inline bool Slot::has_center_var() const
{
    return this != internal_default_instance() && center_var_ != NULL;
}
inline const ::raincom::apa::msgs::Vec2 &Slot::_internal_center_var() const
{
    return *center_var_;
}
inline const ::raincom::apa::msgs::Vec2 &Slot::center_var() const
{
    const ::raincom::apa::msgs::Vec2 *p = center_var_;
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Slot.center_var)
    return p != NULL ? *p
                     : *reinterpret_cast<const ::raincom::apa::msgs::Vec2 *>(
                           &::raincom::apa::msgs::_Vec2_default_instance_);
}
inline ::raincom::apa::msgs::Vec2 *Slot::release_center_var()
{
    // @@protoc_insertion_point(field_release:raincom.apa.msgs.Slot.center_var)

    ::raincom::apa::msgs::Vec2 *temp = center_var_;
    center_var_                      = NULL;
    return temp;
}
inline ::raincom::apa::msgs::Vec2 *Slot::mutable_center_var()
{

    if (center_var_ == NULL)
    {
        auto *p     = CreateMaybeMessage<::raincom::apa::msgs::Vec2>(GetArenaNoVirtual());
        center_var_ = p;
    }
    // @@protoc_insertion_point(field_mutable:raincom.apa.msgs.Slot.center_var)
    return center_var_;
}
inline void Slot::set_allocated_center_var(::raincom::apa::msgs::Vec2 *center_var)
{
    ::google::protobuf::Arena *message_arena = GetArenaNoVirtual();
    if (message_arena == NULL)
    {
        delete reinterpret_cast<::google::protobuf::MessageLite *>(center_var_);
    }
    if (center_var)
    {
        ::google::protobuf::Arena *submessage_arena = NULL;
        if (message_arena != submessage_arena)
        {
            center_var = ::google::protobuf::internal::GetOwnedMessage(
                message_arena, center_var, submessage_arena);
        }
    }
    else
    {
    }
    center_var_ = center_var;
    // @@protoc_insertion_point(field_set_allocated:raincom.apa.msgs.Slot.center_var)
}

// .raincom.apa.msgs.Slot.LockerState locker_state = 9;
inline void Slot::clear_locker_state() { locker_state_ = 0; }
inline ::raincom::apa::msgs::Slot_LockerState Slot::locker_state() const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Slot.locker_state)
    return static_cast<::raincom::apa::msgs::Slot_LockerState>(locker_state_);
}
inline void Slot::set_locker_state(::raincom::apa::msgs::Slot_LockerState value)
{

    locker_state_ = value;
    // @@protoc_insertion_point(field_set:raincom.apa.msgs.Slot.locker_state)
}

// float locker_conf = 10;
inline void Slot::clear_locker_conf() { locker_conf_ = 0; }
inline float Slot::locker_conf() const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Slot.locker_conf)
    return locker_conf_;
}
inline void Slot::set_locker_conf(float value)
{

    locker_conf_ = value;
    // @@protoc_insertion_point(field_set:raincom.apa.msgs.Slot.locker_conf)
}

// float ori = 11;
inline void Slot::clear_ori() { ori_ = 0; }
inline float Slot::ori() const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Slot.ori)
    return ori_;
}
inline void Slot::set_ori(float value)
{

    ori_ = value;
    // @@protoc_insertion_point(field_set:raincom.apa.msgs.Slot.ori)
}

// float ori_var = 12;
inline void Slot::clear_ori_var() { ori_var_ = 0; }
inline float Slot::ori_var() const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Slot.ori_var)
    return ori_var_;
}
inline void Slot::set_ori_var(float value)
{

    ori_var_ = value;
    // @@protoc_insertion_point(field_set:raincom.apa.msgs.Slot.ori_var)
}

// float tilt_angle = 13;
inline void Slot::clear_tilt_angle() { tilt_angle_ = 0; }
inline float Slot::tilt_angle() const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Slot.tilt_angle)
    return tilt_angle_;
}
inline void Slot::set_tilt_angle(float value)
{

    tilt_angle_ = value;
    // @@protoc_insertion_point(field_set:raincom.apa.msgs.Slot.tilt_angle)
}

// float tilt_angle_var = 14;
inline void Slot::clear_tilt_angle_var() { tilt_angle_var_ = 0; }
inline float Slot::tilt_angle_var() const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Slot.tilt_angle_var)
    return tilt_angle_var_;
}
inline void Slot::set_tilt_angle_var(float value)
{

    tilt_angle_var_ = value;
    // @@protoc_insertion_point(field_set:raincom.apa.msgs.Slot.tilt_angle_var)
}

// repeated .raincom.apa.msgs.Vec2 corners = 15;
inline int Slot::corners_size() const { return corners_.size(); }
inline ::raincom::apa::msgs::Vec2 *Slot::mutable_corners(int index)
{
    // @@protoc_insertion_point(field_mutable:raincom.apa.msgs.Slot.corners)
    return corners_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Vec2>
    *Slot::mutable_corners()
{
    // @@protoc_insertion_point(field_mutable_list:raincom.apa.msgs.Slot.corners)
    return &corners_;
}
inline const ::raincom::apa::msgs::Vec2 &Slot::corners(int index) const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Slot.corners)
    return corners_.Get(index);
}
inline ::raincom::apa::msgs::Vec2 *Slot::add_corners()
{
    // @@protoc_insertion_point(field_add:raincom.apa.msgs.Slot.corners)
    return corners_.Add();
}
inline const ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Vec2>
    &Slot::corners() const
{
    // @@protoc_insertion_point(field_list:raincom.apa.msgs.Slot.corners)
    return corners_;
}

// repeated .raincom.apa.msgs.Vec2 corners_var = 16;
inline int Slot::corners_var_size() const { return corners_var_.size(); }
inline ::raincom::apa::msgs::Vec2 *Slot::mutable_corners_var(int index)
{
    // @@protoc_insertion_point(field_mutable:raincom.apa.msgs.Slot.corners_var)
    return corners_var_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Vec2>
    *Slot::mutable_corners_var()
{
    // @@protoc_insertion_point(field_mutable_list:raincom.apa.msgs.Slot.corners_var)
    return &corners_var_;
}
inline const ::raincom::apa::msgs::Vec2 &Slot::corners_var(int index) const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Slot.corners_var)
    return corners_var_.Get(index);
}
inline ::raincom::apa::msgs::Vec2 *Slot::add_corners_var()
{
    // @@protoc_insertion_point(field_add:raincom.apa.msgs.Slot.corners_var)
    return corners_var_.Add();
}
inline const ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Vec2>
    &Slot::corners_var() const
{
    // @@protoc_insertion_point(field_list:raincom.apa.msgs.Slot.corners_var)
    return corners_var_;
}

// float depth = 17;
inline void Slot::clear_depth() { depth_ = 0; }
inline float Slot::depth() const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Slot.depth)
    return depth_;
}
inline void Slot::set_depth(float value)
{

    depth_ = value;
    // @@protoc_insertion_point(field_set:raincom.apa.msgs.Slot.depth)
}

// float depth_var = 18;
inline void Slot::clear_depth_var() { depth_var_ = 0; }
inline float Slot::depth_var() const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Slot.depth_var)
    return depth_var_;
}
inline void Slot::set_depth_var(float value)
{

    depth_var_ = value;
    // @@protoc_insertion_point(field_set:raincom.apa.msgs.Slot.depth_var)
}

// float width = 19;
inline void Slot::clear_width() { width_ = 0; }
inline float Slot::width() const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Slot.width)
    return width_;
}
inline void Slot::set_width(float value)
{

    width_ = value;
    // @@protoc_insertion_point(field_set:raincom.apa.msgs.Slot.width)
}

// float width_var = 20;
inline void Slot::clear_width_var() { width_var_ = 0; }
inline float Slot::width_var() const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Slot.width_var)
    return width_var_;
}
inline void Slot::set_width_var(float value)
{

    width_var_ = value;
    // @@protoc_insertion_point(field_set:raincom.apa.msgs.Slot.width_var)
}

// .raincom.apa.msgs.Slot.OccupyState occupied = 21;
inline void Slot::clear_occupied() { occupied_ = 0; }
inline ::raincom::apa::msgs::Slot_OccupyState Slot::occupied() const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Slot.occupied)
    return static_cast<::raincom::apa::msgs::Slot_OccupyState>(occupied_);
}
inline void Slot::set_occupied(::raincom::apa::msgs::Slot_OccupyState value)
{

    occupied_ = value;
    // @@protoc_insertion_point(field_set:raincom.apa.msgs.Slot.occupied)
}

// float occupied_conf = 22;
inline void Slot::clear_occupied_conf() { occupied_conf_ = 0; }
inline float Slot::occupied_conf() const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Slot.occupied_conf)
    return occupied_conf_;
}
inline void Slot::set_occupied_conf(float value)
{

    occupied_conf_ = value;
    // @@protoc_insertion_point(field_set:raincom.apa.msgs.Slot.occupied_conf)
}

// repeated int32 ref_objs = 23;
inline int Slot::ref_objs_size() const { return ref_objs_.size(); }
inline void Slot::clear_ref_objs() { ref_objs_.Clear(); }
inline ::google::protobuf::int32 Slot::ref_objs(int index) const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Slot.ref_objs)
    return ref_objs_.Get(index);
}
inline void Slot::set_ref_objs(int index, ::google::protobuf::int32 value)
{
    ref_objs_.Set(index, value);
    // @@protoc_insertion_point(field_set:raincom.apa.msgs.Slot.ref_objs)
}
inline void Slot::add_ref_objs(::google::protobuf::int32 value)
{
    ref_objs_.Add(value);
    // @@protoc_insertion_point(field_add:raincom.apa.msgs.Slot.ref_objs)
}
inline const ::google::protobuf::RepeatedField<::google::protobuf::int32>
    &Slot::ref_objs() const
{
    // @@protoc_insertion_point(field_list:raincom.apa.msgs.Slot.ref_objs)
    return ref_objs_;
}
inline ::google::protobuf::RepeatedField<::google::protobuf::int32>
    *Slot::mutable_ref_objs()
{
    // @@protoc_insertion_point(field_mutable_list:raincom.apa.msgs.Slot.ref_objs)
    return &ref_objs_;
}

// repeated .raincom.apa.msgs.Vec2 stop_bar_pos = 24;
inline int Slot::stop_bar_pos_size() const { return stop_bar_pos_.size(); }
inline ::raincom::apa::msgs::Vec2 *Slot::mutable_stop_bar_pos(int index)
{
    // @@protoc_insertion_point(field_mutable:raincom.apa.msgs.Slot.stop_bar_pos)
    return stop_bar_pos_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Vec2>
    *Slot::mutable_stop_bar_pos()
{
    // @@protoc_insertion_point(field_mutable_list:raincom.apa.msgs.Slot.stop_bar_pos)
    return &stop_bar_pos_;
}
inline const ::raincom::apa::msgs::Vec2 &Slot::stop_bar_pos(int index) const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Slot.stop_bar_pos)
    return stop_bar_pos_.Get(index);
}
inline ::raincom::apa::msgs::Vec2 *Slot::add_stop_bar_pos()
{
    // @@protoc_insertion_point(field_add:raincom.apa.msgs.Slot.stop_bar_pos)
    return stop_bar_pos_.Add();
}
inline const ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Vec2>
    &Slot::stop_bar_pos() const
{
    // @@protoc_insertion_point(field_list:raincom.apa.msgs.Slot.stop_bar_pos)
    return stop_bar_pos_;
}

// repeated .raincom.apa.msgs.Vec2 stop_bar_pos_var = 25;
inline int Slot::stop_bar_pos_var_size() const { return stop_bar_pos_var_.size(); }
inline ::raincom::apa::msgs::Vec2 *Slot::mutable_stop_bar_pos_var(int index)
{
    // @@protoc_insertion_point(field_mutable:raincom.apa.msgs.Slot.stop_bar_pos_var)
    return stop_bar_pos_var_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Vec2>
    *Slot::mutable_stop_bar_pos_var()
{
    // @@protoc_insertion_point(field_mutable_list:raincom.apa.msgs.Slot.stop_bar_pos_var)
    return &stop_bar_pos_var_;
}
inline const ::raincom::apa::msgs::Vec2 &Slot::stop_bar_pos_var(int index) const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Slot.stop_bar_pos_var)
    return stop_bar_pos_var_.Get(index);
}
inline ::raincom::apa::msgs::Vec2 *Slot::add_stop_bar_pos_var()
{
    // @@protoc_insertion_point(field_add:raincom.apa.msgs.Slot.stop_bar_pos_var)
    return stop_bar_pos_var_.Add();
}
inline const ::google::protobuf::RepeatedPtrField<::raincom::apa::msgs::Vec2>
    &Slot::stop_bar_pos_var() const
{
    // @@protoc_insertion_point(field_list:raincom.apa.msgs.Slot.stop_bar_pos_var)
    return stop_bar_pos_var_;
}

// float stop_bar_conf = 26;
inline void Slot::clear_stop_bar_conf() { stop_bar_conf_ = 0; }
inline float Slot::stop_bar_conf() const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Slot.stop_bar_conf)
    return stop_bar_conf_;
}
inline void Slot::set_stop_bar_conf(float value)
{

    stop_bar_conf_ = value;
    // @@protoc_insertion_point(field_set:raincom.apa.msgs.Slot.stop_bar_conf)
}

// float stop_bar_btm = 27;
inline void Slot::clear_stop_bar_btm() { stop_bar_btm_ = 0; }
inline float Slot::stop_bar_btm() const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Slot.stop_bar_btm)
    return stop_bar_btm_;
}
inline void Slot::set_stop_bar_btm(float value)
{

    stop_bar_btm_ = value;
    // @@protoc_insertion_point(field_set:raincom.apa.msgs.Slot.stop_bar_btm)
}

// float stop_bar_top = 28;
inline void Slot::clear_stop_bar_top() { stop_bar_top_ = 0; }
inline float Slot::stop_bar_top() const
{
    // @@protoc_insertion_point(field_get:raincom.apa.msgs.Slot.stop_bar_top)
    return stop_bar_top_;
}
inline void Slot::set_stop_bar_top(float value)
{

    stop_bar_top_ = value;
    // @@protoc_insertion_point(field_set:raincom.apa.msgs.Slot.stop_bar_top)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif // __GNUC__

// @@protoc_insertion_point(namespace_scope)

} // namespace msgs
} // namespace apa
} // namespace raincom

namespace google
{
namespace protobuf
{

template <>
struct is_proto_enum<::raincom::apa::msgs::Slot_Type> : ::std::true_type
{
};
template <>
inline const EnumDescriptor *GetEnumDescriptor<::raincom::apa::msgs::Slot_Type>()
{
    return ::raincom::apa::msgs::Slot_Type_descriptor();
}
template <>
struct is_proto_enum<::raincom::apa::msgs::Slot_LockerState> : ::std::true_type
{
};
template <>
inline const EnumDescriptor *GetEnumDescriptor<::raincom::apa::msgs::Slot_LockerState>()
{
    return ::raincom::apa::msgs::Slot_LockerState_descriptor();
}
template <>
struct is_proto_enum<::raincom::apa::msgs::Slot_OccupyState> : ::std::true_type
{
};
template <>
inline const EnumDescriptor *GetEnumDescriptor<::raincom::apa::msgs::Slot_OccupyState>()
{
    return ::raincom::apa::msgs::Slot_OccupyState_descriptor();
}
template <>
struct is_proto_enum<::raincom::apa::msgs::Slot_CornerOrder> : ::std::true_type
{
};
template <>
inline const EnumDescriptor *GetEnumDescriptor<::raincom::apa::msgs::Slot_CornerOrder>()
{
    return ::raincom::apa::msgs::Slot_CornerOrder_descriptor();
}

} // namespace protobuf
} // namespace google

// @@protoc_insertion_point(global_scope)

#endif // PROTOBUF_INCLUDED_apa_5fmsgs_2fslot_2eproto
